### ISSUE TITLE
Support absolute paths to resources in the filesystem

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1007]
![error](https://cloud.githubusercontent.com/assets/25212/9592520/9ae1bdc8-4ff8-11e5-9500-018ff23dcfd2.gif)

**Comment by flukeout** [comment]
So it turns out that having this code in the stylesheet breaks things..
`` background: url(/img/pencil-icon.svg);``

It complains about paths needing to be absolute...

![image](https://cloud.githubusercontent.com/assets/25212/9592611/92866d62-4ff9-11e5-8810-18945d4eb30e.png)

Losing work seems to be related to the editor not auto-saving once it's in this state.

**Comment by humphd** [comment]
Try dropping the initial `/` in the path, so ti's relative vs. absolute.

**Comment by gideonthomas** [comment]
Hmm but the not saving is kinda bad! It seems like brackets does not write to disk if it encounters an error?

**Comment by humphd** [comment]
This was fixed today by https://github.com/humphd/brackets/commit/ca10c87443651bf03a9a0fbfba0c81563745f9cb.  We won't "crash" anymore when rewriting a CSS file that has a `url(..)` we can't find.

**Comment by flukeout** [comment]
@humphd Cool - but will the image show if it is absolutely referenced?

**Comment by humphd** [comment]
Using an absolute path like that is a bad idea.  I'm not sure whether we should force it to work.  @gideonthomas, what do you think?  If I go to the "Keep Calm" project and add a `background-image: url(/crown.svg)` I get this:

![screenshot 2015-09-11 12 56 39](https://cloud.githubusercontent.com/assets/427398/9820836/a2044dac-5884-11e5-97ca-b9135e281162.png)

**Comment by gideonthomas** [comment]
I agree I don't think we should support absolute paths. From what I read online, it seems that most web devs agree that it is better to use relative urls if the resource is on the same server and absolute urls if the resource is on the web (a different server).
I think it's good that we don't crash on absolute paths but supporting it seems to be unnecessary.

Having said that, I do think we should be careful about relative urls as well especially wrt publishing. If I do `<img src="../../someone-elses-username/project-id/resource-name">` we would be accessing someone else's published resources which might not be desirable. On the other hand maybe we shouldn't care since published resources are meant to be public!

**Comment by flukeout** [comment]
Here are my thoughts
* I think absolute paths should work, because they generally do in other circumstances
* If we want to discourage people from using them, we should provide some kind of helpful messaging or guide when we detect absolute paths so people can fix them
  * This would require a bunch of UX and UI work, of course - but it's something we're going start tackling soon anyway

**Comment by DanForever** [comment]
Here's my use case, for what it's worth:

I'm using google app engine, so I've put all my stylesheets in the same root directory ("/stylesheets") and set up a handler so that www.mywebsite.com/stylesheets internally points at where my css files are stored, that way, when my url is www.mywebsite.com/some/interesting/page/of/sorts/, it'll still look for the files in the correct place, and not www.mywebsite.com/some/interesting/page/of/sorts/stylesheets/ which is a url that doesn't map to anything

**Comment by gideonthomas** [comment]
@jbuck absolute paths will break things while publishing! Published urls usually look like this: `https://d157rqmxrxj6ey.cloudfront.net/<username>/<publishedId>/`. Do you have any suggestions on how to possibly get around this?

**Comment by jbuck** [comment]
Some thoughts from IRC

```
[12:25:59]  <jbuck>	Q: Bramble does rewriting of URLs within the preview pane. Does it save those rewritten URLs to the publish server as well?
[12:26:22]  <jbuck>	if the answer to that is "no", then is there the possibility of making that answer "yes"?
[12:27:35]  <jbuck>	(I guess also, does it make sense to approach it this way...)
[12:31:35]  <jbuck>	gthomas: and also, do absolute URLs work in the preview pane currently?
[12:32:21]  <gthomas>	So, they don't currently work, but we were thinking about fixing that (it would involve rewriting the urls)
[12:32:45]  <gthomas>	The problem with saving that to the publish server is that it will be hard to revert when we remix
[12:33:40]  <gthomas>	also, the path in bramble *won't* be the same as the path when we publish
[12:34:15]  <gthomas>	in bramble, the path will be something like /<userid>/projects/<projectid>/whatever
[12:34:44]  <gthomas>	but what's actually stored in the publish db is /whatever
[12:35:09]  <gthomas>	and what is *published* is /<username>/<publishedId>/whatever
```

**Comment by jbuck** [comment]
It sounds like any solution we do needs to support three things:

1. Have absolute URLs work in the preview pane
2. Have absolute URLs work in the published project
3. Have absolute URLs work in a remixed project

**Comment by gideonthomas** [comment]
One suggestion is the following:
```irc
13:28 gthomas: so we inject the remix script into the published file before we publish it. So, that means that what's in the publish.wm.org db does not have the remix script, but what's on AWS has the remix script
13:29 gthomas: can we maybe do the same to rewrite the urls before publish and prepend the bucket
13:29 gthomas: so that change will only be on AWS
13:29 jbuck: yeah, that might be a possibility
13:29 gthomas: it might increase the publishing time by quite a bit though
13:30 gthomas: unless, we do it in a script that we can inject
```

**Comment by humphd** [comment]
From the [URL spec](https://url.spec.whatwg.org/#syntax-url-path-absolute), what we're trying to decide on here is whether we want to support **path-absolute-URLs** (starts with `/`) or **path-relative-URLs** (can't start with `/`).

I continue to think this is a bad idea, since the meaning of a path-absolute URL is that it belongs to the server root:

```
var a = document.createElement('a')
a.href = '/crown.svg'
a.href ==> "https://thimble.mozilla.org/crown.svg"
```

We don't support this, so making it work is going to mean a bunch of gymnastics to rewrite such URLs so that they are actually relative.  Looking around the web, I see all kinds of examples of projects that agree: LESS is one, which won't support absolute paths.

We make no commitment to publish your site/app at the root of our web server, so coding it as though you can expect this is a bad idea imo.

cc @Pomax
