### ISSUE TITLE
Migrate most popular thimble.webmaker makes to thimble.mozilla projects

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1050]
After reading @LauraReynal 's and @Saallen notes from using Thimble today it made me think we may want to move over the ten or so most popular makes from old Thimble.

I remember @adamlofting publishing a list somewhere of the popular makes.

**Comment by hannahkane** [comment]
Great idea, as usual. We're intending to migrate ALL Thimble makes at some point, as well as create gallery tools for viewing/filtering projects by certain criteria, which could include popularity, though we'll have to figure out what that means in the new Thimble paradigm. At a minimum, we could have a view of staff-curated projects.

Alright if I close this, @jgmac1106, since I think it's represented in the roadmap (http://bit.ly/1Q9yokU)?
