### ISSUE TITLE
Figure out UX for switching between JS files

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1067]
In the following gif, I have to work with two JS files - `main.js` and `lib/coordinates.js`. I have `main.js` included in my `index.html` file and the `lib/coordinates.js` included in my `lib/coordinates.html` file. Basically, switching between the two js files can have a weird UX (or maybe it's just me).

My preview shows `index.html` rendered and I go to the `main.js` file and make some changes - I see the changes reflected in the preview. Now, I switch to the `lib/coordinates.js` file to make a quick update. I still see the `index.html` file rendered into the preview while what I want is the `lib/coordinates.html` file rendered since I am editing another file related to it.

I was thinking maybe we can maintain a relationship structure (kinda like what we do with HTML-CSS files) between JS files and HTML files as well so that when we switch between JS files, instead of just reloading the current preview, we load the related HTML file and render it in the preview.

cc @humphd @flukeout 

![js-stuff1](https://cloud.githubusercontent.com/assets/5816130/9765575/f16f4cb4-56e2-11e5-960b-26a70f6fc2ac.gif)

**Comment by humphd** [comment]
So, to summarize, you expect that switching to a non-HTML file in the editor would change the preview to show the related HTML file for this resource.  I think that's an edge case, since having multiple HTML files at all is not our standard approach.  Also, how do you deal with a file that's linked to more than one HTML file, for example, an image?

**Comment by humphd** [comment]
Too hard, no :)
