### ISSUE TITLE
Figure out UX for reloading JS changes

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1068]
If I have a JS file open and make changes to it, it reloads the preview window every 5s (due to file saving). This looks pretty bad especially if we have code like `alert("HI")` or something! It also can break the preview if it saves exactly when we write something like `aler` and stays broken until 5s later.

We probably need a reload JS button or something and disable JS reloading by default.

**Comment by humphd** [comment]
I'd like to suggest that we offer a way to turn off automatic reloading of the preview, but have it be on by default.  When it's off, we could do a few things:
* flash the reload button, or have it change colour and stay that colour until the user refreshes
* put an overlay over-top of the preview to indicate that it's out of sync with the editor, and needs manual updating

The back-end for this is pretty easy to do, since we control when the preview reloads, and could choose to send an event to the host app instead.

**Comment by humphd** [comment]
I think the fixes we have now in the UI, plus my "run JS on reload" will solve this.  Closing.
