### ISSUE TITLE
Differences between preview render and published page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/thimble.webmaker.org#1091]
Related to #1043, if you import a Webmaker project, it will render *some* things on the page improperly (like all of the Webmaker dressing). But, when you publish, it appears.

**Comment by secretrobotron** [comment]
e.g. http://bramble-staging.s3-website-us-east-1.amazonaws.com/cepheid/303/glerp.html

Even in that published render, some of the css/js doesn't work anymore.

**Comment by humphd** [comment]
Yeah, this is a nice meaty test case.  I'll debug this and see what's happening.

**Comment by humphd** [comment]
This turns out to be a mix of two things:
* missing resources in the zip file of the site, and it can't find what it needs (in this case it's looking for `background: url(../img/x.svg) center center contain no-repeat;` and can't locate `x.svg`.  There seem to be a lot of links to files that aren't there.
* our CSSRewriter being too aggressive in how it bails on that error

**Comment by secretrobotron** [comment]
> missing resources in the zip file of the site

Hmm yeah, I noticed a bit of that. Filed https://github.com/mozilla/webmaker-core/issues/653 to see if we can fix that from the other end too. Any pointers you can give?

**Comment by humphd** [comment]
I've done a fix in Bramble for this.  If your project is missing files, it's because they weren't included.  Unless you're saying that they were in your original project but didn't get published?

**Comment by humphd** [comment]
@secretrobotron please re-open this if you think it's us doing the wrong thing with your exported project.  I think this is "missing files in an exported project."

**Comment by secretrobotron** [comment]
:+1: will do. Thanks @humphd.
