### ISSUE TITLE
(re)publishing through the publish menu is confusing

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/thimble.webmaker.org#1093]
If I'm working on a previously published Thimble project and I want to re-publish it, I would think clicking on the Publish button would get that done. But, a menu shows up instead, requiring me to hit "update published version".

1) Are you collecting this sort of feedback somewhere already?
2) What's the right way to user-test to find out if it's a problem for other people?

**Comment by flukeout** [comment]
Just to re-iterate, what @secretrobotron is complaining about is basically having to hit two buttons to update his published project, instead of just once via an explicit "Update published" button, for example.

He was doing this because:
* The preview window is too small
* He didn't trust the preview window

We could also solve this by making it easier to get a full screen preview of your project.

We have run some usertesting tests to check in on this interaction and it didn't raise too many flags. However, this type of stuff is hard to test in a testing setting because it's kind of specific to having one project that you're constantly previewing.

**Comment by humphd** [comment]
See also #784.
