### ISSUE TITLE
Can You Dump the Meta Viewport Tag in New Files?

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.webmaker.org#1103]
Can you get rid of the 

     <meta name="viewport"...

in the template you use for new files? People learning HTML will find it to be confusing boilerplate. At the very least, the syntax highlighter should fade it out so that it's clear that it's "useless boilerplate" that they can ignore.

I also think you should remove the

     <meta charset

tag and simply stick a UTF-8 BOM at the front of the document, but it's a short tag, so I can ignore it.

**Comment by humphd** [comment]
The reason we did this is because people would create content in the editor, preview it in the mobile view, and then publish and run it on their actual phone, only to find that it doesn't render anything like they expect.  Without specifying the `viewport` sizing, mobile browsers won't do what users expect.  So either we surprise a learner with a line of code they don't understand yet, or we surprise them with a web page that doesn't render properly on mobile.

cc'ing @flukeout for some UX thoughts about how we could do this better.

**Comment by my2iu** [comment]
Well, the fact that it doesn't render "properly" on mobile could be a teachable moment about how browsers are free to render things however they want, and about how one fruity company's poorly thought-out mobile web extensions have now doomed us to forever needing to stick a useless tag at the front of every html file to get things to work right on phones.

But, whatever you find works best is fine with me. I lean towards not having complex gobbledygook that you have to tell kids to ignore. That sort of stuff becomes especially problematic with younger kids who aren't that good at ignoring details and focusing on the bigger picture. 

But kids do like their phones nowadays... and most teachers don't have the expertise to know to tell kids to add that extra tag into their documents to fix things...

**Comment by humphd** [comment]
I think we've decided to keep this, it's working well for users on mobile. Closing.
