### ISSUE TITLE
Require File Naming Before Publishing

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1108]
I used Thimble yesterday for the first time in my class. No student had previously worked in HTML.

 After watching how they work I think we should require you to save a name change for a new project or a remixed project before publishing. Almost everyone kept the file title of the original meme and when starting for blank just published an untitled project.

**Comment by humphd** [comment]
I think we should consider dropping the title completely.  Similar to the project's description, people don't seem to want to fill this in.  I don't blame them, since it's exterior to the web page.  Also, it isn't clear to someone making something in Thimble how it will get used (i.e., there is no visible utility).  We only tack it on when we publish, and that's not obvious, since we don't give you any sense that this will happen.

See also #1107.  cc @flukeout

**Comment by jgmac1106** [comment]
That actually makes sense. I find myself rushing descriptions as well.

Maybe this feature (Title and Description) would work better on the
profile/gallery page. So as teacher I would group and add titles to
projects I want to curate and/or promote. A user could also use the
profile/gallery to create a portfolio of material they want to
curate/promote.

**Comment by humphd** [comment]
I'm going to close this and we can follow up in #1107 as we finalize that design.
