### ISSUE TITLE
Project with title - shows as having no title after publish

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.webmaker.org#1151]
Even though this project has a title in the code view, and in the projects view the published link shows as 'untitled'. Tried closing and opening browser, changing title again.  

https://d157rqmxrxj6ey.cloudfront.net/sunnydeveloper/15587/
![random_community_challange_-_generator_-_2015-09-24_12 31 20](https://cloud.githubusercontent.com/assets/60618/10084417/3411c8cc-62b8-11e5-94f3-35adf207a8ad.png)

**Comment by gideonthomas** [comment]
Hmm, I see a title when I click on that link. Did you first publish it without a title? Maybe your browser showed a cached version of the page when you refreshed it.

**Comment by emmairwin** [comment]
@gideonthomas it eventually did show, although I'm not sure what triggered it. could be caching, but other updates showed which was strange.

**Comment by humphd** [comment]
We haven't seen a lot of this happen since this bug, and at the time that you reported it, we had a bunch of issues causing timeouts on the publishing server.  I feel like what we see here is the result of that.  I'm going to close this, and ask that we re-open or file a new bug if it starts happening again.
