### ISSUE TITLE
Add Google Analytics tracking to Published projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1164]
We don't have any tracking baked into Published projects but I think we should.

I was thinking that we could set up a separate "site" under Google Analytics so we could track these independently from the Thimble homepage and editor.

@adamlofting Thoughts?

We could inject the tracking code along with the details bar and remix button for published projects.

**Comment by flukeout** [comment]
@gideonthomas Here's the tracking code...
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68630113-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by adamlofting** [comment]
Please hold-off from adding this to published projects for now. This needs a little more planning.

Am I right in thinking the published projects are still accessed via a cloudfront URL?

The chose domain name has an impact on cookies which impacts on how the user journeys are tracked between related properties (e.g. Editor to published project, and vice versa).

**Comment by flukeout** [comment]
Hey @adamlofting, for now it's on cloudfront, but will eventually live on ``thimbleprojects.org``. I'm not sure about the timeline for the switch, but when it happens we can set up cross-domain tracking.

Are there any downsides to adding some basic tracking in the interim before we sort this out?

**Comment by flukeout** [comment]
@adamlofting will investigate potential concerns with GA cookies set on stuff hosted via CloudFront.

**Comment by flukeout** [comment]
@adamlofting Have you had a chance to look into this? Are there any questions the team can answer to help the process?

**Comment by hannahkane** [comment]
@adamlofting - would it be useful to set up a quick conversation about this? I want to understand the blockers better.

**Comment by adamlofting** [comment]
Sorry for the hold up. I've looked into this in more detail this morning.

We can add GA tracking while this is on cloudfront, and then switch the domain to thimbleprojects.org in the future. But we'll use a new `GA-xxx` id for this.

I've requested a new GA property from the MoCo team that will accept GA data from the domains `d157rqmxrxj6ey.cloudfront.net` and `thimbleprojects.org` - [See bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1220096).

The cloudfront domain is OK because the default GA tracking code will use the full `document.location.hostname` for the cookie. And our CF subdomain is fixed across all projects. [GA docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id)

Side note (not a blocker for this ticket)... It would be interesting to think through the implications of users adding their own GA tracking into their projects. And, also to think about how we could expose our GA data to them in an automated way like you can by adding a `+` to a bit.ly URL e.g. 
* https://bitly.com/18vyjIf 
* and access the stats here https://bitly.com/18vyjIf+
