### ISSUE TITLE
Thimble editor will not load

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1179]
The thimble editor will not load. Just the spinning Thimble (too early to call spinning thimble of death? or is that this trope is  too tired).

I have tried a few times and shut down the browser. Didn't delete cookies.  If I navigate to my projects a new untitled project is there for each time I try.

**Comment by humphd** [comment]
What's on your error console?  I can't reproduce there (it's loading for me).  Also, which OS/browser?

**Comment by jgmac1106** [comment]
Works in Firefox for me. Not on Chrome 46.0.2490.71 on 10.10.4 Yosemite.

**Comment by jgmac1106** [comment]
Worked fine after deleting cached files and cookies.

**Comment by DraeJR** [comment]
I had the same problem I'm on 10.10.2 Yosemite using Chrome. 
I could not load projects and instead got the loading thimble-symbol on repeat. 

I found this thread and I deleted cashed files and cookies

Currently the whole site will not load and instead gives me this error message:

" Application Error: An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your log for details."

**Comment by humphd** [comment]
Thanks for all the follow-ups here.  We've been tracking some scaling issues on the Thimble publish server, which is causing timeouts (the problem was an influx of a lot of new users all at once, which swamped our servers).  We've turned on autoscaling, so it *should* scale up/down automatically as needed on the backend.  We continue to monitor and tweak things, and if you find that you're having issues, please do keep letting us know.

**Comment by jgmac1106** [comment]
You will have to give me a quick tutorial on an error console some time.
Have no idea what that is.
