### ISSUE TITLE
Deal with published projects without a root level index.html file

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1203]
First, let's grab recently edited published projects...

``select * from projects where published_id is not null order by date_updated desc limit 10``

Here's one of the records, with a publish_url...

![image](https://cloud.githubusercontent.com/assets/25212/10853428/3a3ae04c-7ef3-11e5-9250-9b5326019079.png)

https://d157rqmxrxj6ey.cloudfront.net/17706/10407

However, it doesn't exist when you try to view it...

![image](https://cloud.githubusercontent.com/assets/25212/10853444/4d35ebf6-7ef3-11e5-8aaf-317dc288ee00.png)

This happens pretty often, sometimes half of the projects returned from the query above are 404-ing, are we not removing ``publish_url`` when someone unpublishes their project?

**Comment by Pomax** [comment]
for the question, perhaps @gideonthomas knows. But in general, this query result validation would actually be really good to have running as a cron job, to check whether our db is in sync with the actual data on the internet.

**Comment by humphd** [comment]
I'd like to know if there is an `index.html` or not.

**Comment by humphd** [comment]
@gideonthomas can you get us some data on this?

**Comment by flukeout** [comment]
It doesn't

![image](https://cloud.githubusercontent.com/assets/25212/10860573/66ce310c-7f27-11e5-91d2-1ba49dd3b591.png)

**Comment by humphd** [comment]
So what should we do here?  Thimble is doing the right thing, but not what a user will expect.  Should we hand-out a different URL to the user, that's deeper in their tree?  Should we provide a default `/index.html` file that helps them get to the one they probably want?  Something else?

**Comment by Pomax** [comment]
hmmm... this feels like a teaching opportunity: if users publish without a top level index.html we could tell them that'll be a problem, and ask if we should autogenerate this so that their published site will automatically redirect to the index.html we did find in their project?
```
<!doctype html>
<html>
  <head>
    <meta refresh="link to real index.html">
  </head>
</html>
```

**Comment by humphd** [comment]
I'd be interested to hear what @hannahkane, @ldecoursy, and others have to say about this.  There are various technical solutions we could go with.

**Comment by ldecoursy** [comment]
Not sure I'm clear what this one is about, sorry!

**Comment by humphd** [comment]
@ldecoursy if a person renames `/index.html` to `/about-me.html`, or if they delete `/index.html` and create `/data/index.html` when they go to the published link we give them, they will get a 404, since there will be no `/index.html` file present.

Here's an example:

https://d157rqmxrxj6ey.cloudfront.net/acuevas03/26275

With the old thimble, you only ever had a single web page, so we could always just publish and show you your single page.  With the new Thimble, you can have lots of pages, and the web server we host things from will default to give you `/index.html` when you ask for `/` (i.e., when you enter https://d157rqmxrxj6ey.cloudfront.net/acuevas03/26275 you are really saying https://d157rqmxrxj6ey.cloudfront.net/acuevas03/26275/index.html, but that file doesn't exist so they get 404).

**Comment by flukeout** [comment]
@humphd When I load up a path on my own website that doesn't have an index.html file, I see the following... 

![image](https://cloud.githubusercontent.com/assets/25212/10888350/94506012-8140-11e5-8105-9b0ab8eab7ea.png)

Which I think is actually pretty great. It tells me that yes, I have stuff on the web, but it's buried in a folder that I need to add to my path.

Can we do something similar? We can even add a message to the top of this view that helps people understand why they aren't seeing the file they probably thought they would.

We could generate this view at the root level for published projects when a project is published without an index.

**Comment by humphd** [comment]
Yes, we can do something like this--I've already got code for it in another project.

**Comment by jbuck** [comment]
I see several options here:

1. For each directory a project has publish an index.html file that lists the files in each directory
2. Publish a list of files in each project directory to a json file, and rewrite the current error page to dynamically create a list of files after loading that json file
3. Allow anyone to list the s3 bucket and rewrite the error page to dynamically list the S3 bucket for files

All three options are okay, but I'm leaning towards 2 & 3.

**Comment by hannahkane** [comment]
Agree showing the directory is good, but definitely want to help the user understand why they might not be seeing what they expect to see. Maybe something like, "This project is displayed as a list of files because it does not have a default page (that is, a file called index.html). Learn more here" and we could link to a particular FAQ in Sumo.

**Comment by Pomax** [comment]
To build on @hannahkane's point, where we understand autoresolution to index.html is a deliberate decision made at the server level, to normal people, it's magic, so it's good to adress it and if that means a dir listing: that might be good solution as long as we explain what they're seeing.

As presentation and publishing to the web has gotten more opaque, people have become very unfamiliar with dealing with "unexpected" things, so just seeing a dir listing, or even something we thing is trivial like dev tools opening, is enough to confuse them into thinking their internet experience broke.

It is important that we don't forget that a large portion of thimle users have no idea (nor care about) how their "site" works from a serving perspective, and anything we do will need to come with some education on why they're getting what they're getting. For a dir listing, at the very least let's not just show files, but also a nice friendly text up top:

"Shouldn't there be a page here? Well, actually, no. {{username}} published their project without a master `index.html` file, which is necessary for a URL without a filename at the end to "just work": your browser will actually load up a file called index.html."

Which then raises the question: what benefit does seeing a dir listing offer the user? Do we expect them to go hunting for an index.html or other html file somewhere? Are we offering this primarily for the person who published, or for the visitors? If the first, we should educate people during the publish step, ideally in a way that makes it impossible to publish without an index.html, even if that index.html meta-refreshes to the real page. Knowing how your pages "route" is an important thing to learn if you're actually publishing a website.

If we do this for visitors, I strongly doubt a dir listing will mean anything to them; I expect users to go "oh there is no page here, just junk" and close the tab, instead of going on a (possibly wild goose) chase for a page that can be loaded.

**Comment by hannahkane** [comment]
+1 to Pomax's point. Can we prevent this from happening in the first place, at the point when an index-less project is about to be published?

**Comment by humphd** [comment]
"Let's explain to the user what we're doing" says @hannahkane.  Could be at the point of publishing, or at the dir listing.  @flukeout will do some work on how to make this happen, what our messaging should be.

**Comment by flukeout** [comment]
@flukeout to break this into two tickets:
* One for showing a directory structure (with message)
* One for indicating to the user at publishing that they'll probably want index.html in their root

**Comment by flukeout** [comment]
Sounds like we're agreed on how to proceed here. I've split this issue into two tickets

* #1260 - Show a directory view when there's no index.html page
* #1261 - Warn users there's no index.html when they publish
