### ISSUE TITLE
Design forms

### ISSUE THREAD

**Issue by Timboliu** [mozilla/thimble.webmaker.org#1206]
Will Thimble make it easy to design forms (see link below) in the future?

http://www.qualitycodes.com/tutorial.php?articleid=15&title=Form-Design-Using-CSS-and-HTML

**Comment by humphd** [comment]
The tutorial you link above works perfectly in Thimble.  Is there something you were trying that wasn't working?

**Comment by Timboliu** [comment]
I can copy past the HTML code in Thimble, but I was wondering if Thimble will make it more easy to design forms in the future?

**Comment by humphd** [comment]
If you mean, will we have visual tools for doing drag-and-drop style UI editing, no, there are no plans for this.

**Comment by Timboliu** [comment]
This is exactly what I mean.
It's probably very hard to create a drag-and-drop style UI editor. Is this the main reason why Mozilla does not have any plans for this? And another question: who decides what functionality is created first. Do the developers of Thimble decide this? How are they making decisions? Is it based on research?

**Comment by humphd** [comment]
Indeed, doing drag-and-drop style HTML editors is hard, and is outside the scope of what Thimble wants to be, which is a tool specifically aimed at teaching HTML, CSS, and JS.

In terms of how things get decided, there is a team of people who actively work on Thimble within Mozilla, and they take input from the community, as well as do user testing and research on what to add or improve.  I'd encourage you to file bugs like this for things you think we should add, with the proviso that we are a small team, and not able to build everything our community wants :)  But when we can, we try to add the features that will help people teach and learn the web.

I'm going to close this bug, since we aren't going to move forward with visual form editing.
