### ISSUE TITLE
history.back() does in-iframe nav, but does not sync the editor

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#1236]
If I have two files like index.html and index2.html, with a button with `history.back()` on the second page, and a link `<a href="index2.html">go</a>` on the first, then clicking the link with index.html loaded navigates me to the index2.html file both in the preview and in the editor. However, clicking the history.back button in index2.html will navigate the iframe back to index.html, but the editor will still show index2.html

**Comment by gideonthomas** [comment]
`clicking the link...navigates me to the index2.html file both in the preview and in the editor` - It's interesting that this happens since I'm no sure we actually implemented this in brackets (I might be wrong here; @humphd might know about this better).
@Pomax do you have any thoughts on what "link navigation in the preview" UX should look like (including stuff like links inside linked pages, `history.back`, etc.)?

**Comment by gideonthomas** [comment]
Don't think we're going to be supporting chained links and history navigation in the preview for now.
