### ISSUE TITLE
Invent better UX for when someone shares the URL of their unpublished project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1259]
Right now, when I'm signed in and editing a project, I see this in my browser's address bar:

![image](https://cloud.githubusercontent.com/assets/25212/11256572/77aab606-8e01-11e5-8fa6-0f1e248da3dc.png)

I may think to myself, I can send this link to @Pomax so he can see what I'm working on. If I do, and he loads it up, it turns into this for him..

![image](https://cloud.githubusercontent.com/assets/25212/11256604/a4d43f3a-8e01-11e5-9270-51578715f9fe.png)

And essentially starts a brand new project. Which is not what I wanted.

**SO** Can we make this better?

* **Option 1** - We can load up what was in my editor at the time and start a remix of it for Pomax
* **Option 2** - We can warn Pomax that the link he's trying is to a draft of a project and wont work and ask him to tell me to publish my project first
  * We could show a list of my already-published projects too
* **Option 3** - We could try to see if there is a published version of that project associated with that URL and open that and then allow Pomax to remix it manually.

Option 1 is cool but a little problematic...
* We've created an expectation that only Published projects are 'live on the web'
* It means that I can view someone's work that hasn't been published yet

The act of sharing the link **does** create a moment that indicates you want this stuff to be public, but you have no way of shutting that off after. As long as Pomax has that URL, he can check in on my draft whenever he wants.

@hannahkane @Pomax @humphd Thoughts?

**Comment by humphd** [comment]
Some random thoughts:

* should we change the word "anonymous" to "private" or "local" or "unpublished" or something else that better indicates that you can't share this?  What about "draft"?  The idea of making a draft of something
* should we follow Google's lead with URLs on Photos, where you can get a "Share" link for a photo, and then give that to someone?  Basically the idea would be to decouple the URL from who you are, so people can't just randomly get at your unpublished project.

In the end, it's really tricky to both support unpublished, and therefore, un-remixable projects, and also have URLs always work.  I kind of like your idea of displaying a message to the user that says, "This project isn't remixable because it hasn't been published by the author yet...", which gives some info about the solution.

**Comment by hannahkane** [comment]
Would like to understand the use case better. Are you sharing with Pomax because you want him to be a collaborator - you want him to be able to edit and/or comment? Are you sharing with him because he wants to remix it himself? Are you wanting to share the final project (not necessarily the code), but don't want it to be visible to just anyone yet?

**Comment by gideonthomas** [comment]
Closing so that we can continue the discussion in https://github.com/mozilla/thimble.webmaker.org/issues/1120
