### ISSUE TITLE
Allow anchor/target navigation within tutorials

### ISSUE THREAD

**Issue by chadsansing** [mozilla/thimble.webmaker.org#1277]
To experiment with tutorial design and user-driven, non-sequential teaching and learning, we need to enable anchors and targets or another navigation solution inside Thimble tutorials.

Issue filed in response to anchors and targets not working here: https://d157rqmxrxj6ey.cloudfront.net/chadsansing/16686/.

[Back to issues.](https://github.com/mozilla/thimble.webmaker.org/issues)

**Comment by flukeout** [comment]
Agreed - I wasn't able to get anchors working in your project at all, @chadsansing 

However, in another project they work in some circumstances, Remix this project and check it out:
https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/16448/

When you first open the tutorial and click the first linked bullet item, the tutorial opens in a new tab. However, if you first click the 'tutorial.html' file in the file view, and THEN click the same link, it behaves as expected. Something weird is going on.

@humphd

**Comment by jgmac1106** [comment]
Here is the updates project where I was trying to do anchor links:
https://thimble.mozilla.org/user/jgmac1106/64926

I meant to update the same project but accidentally remixed my file rather
than editing my current file.

**Comment by gideonthomas** [comment]
@humphd I'm a bit confused about some of the code re: link navigation.
[Out here](https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/nohost/HTMLServer.js#L143-L157), you add your anchor tag manipulation script **only** if there isn't a live doc. In most cases, a live doc exists. So most of the time, the script will not be injected and a link like `<a href="https://google.com">` will fail to load because of CORS. Is this a bug?

**Comment by gideonthomas** [comment]
Also, @humphd, do you know why we/brackets injects a `<base>` tag with the thimble url into the preview iframe? That seems to be the cause of this issue

**Comment by humphd** [comment]
@gideonthomas the injection of that code happens in 2 places: the one you found, and also here: https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/lib/PostMessageTransport.js#L182-L199, which gets called by the LiveDev stuff here https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js#L216-L227.  The reason I also do that one for non-instrumented pages, is that I want the link manager script to get included if for some reason we aren't serving a live doc.  I can't remember when this happens, but it's an edge case we hit (it might be for tutorials, actually, where you show one page, but don't have it open in the editor).

The `<base>` tag is to deal with the fact that HTML pages served from Blob URLs don't allow protocolless URLs to be used.  So you can't do `<script src="//cdn.foo.com/jquery.js">` and have it do what you want (i.e., pick up the protocol of the hosting page and use that).  The only way around this is to use a `<base>` tag, which allows the HTML parser to determine a protocol to use at runtime.  What we use for the URL in the `<base>` tag is totally up to us, since we don't ever use it for anything other than forcing a protocol on such URLs.

**Comment by gideonthomas** [comment]
@humphd Ideally, we would want to set the base to the blob url of the iframe since that would fix this anchor navigation issue. Unfortunately, that forces the protocolless URLs to use a blob protocol (I think?) which would screw things up right?

**Comment by gideonthomas** [comment]
@humphd I guess one way to get around this is to special-case `#frag-id` anchor hrefs to not work in its default manner and instead make it do what we want it to do. Thoughts?

**Comment by gideonthomas** [comment]
Note to self: Tutorials don't have a livedoc until you open the `tutorial.html` file first
