### ISSUE TITLE
Unpublishing a project, and then republishing creates a different-than-before URL for the published project 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1280]
@gideonthomas What are your thoughts on this? I was under the assumption that you'd just always get one URL for a given project, if you unpublished and republished, it would restore it to the original URL.

Currently it seems to increment the URL by one, so that if someone has your previously published URL, they'll need the new URL to see your changes.

Is it possible to always use the same URL, sort of reserve it for that project?

**Comment by gideonthomas** [comment]
So our design did not allow us to reuse ids in the publish database. We can think of ways to keep using the same url (for e.g. deleting the `publishedFiles` but not the `publishedProject` and instead adding a flag to indicate that it has been unpublished). But tbh, I don't know if this would be the most pressing issue especially since it would involve a bunch of work with migrations and changes to the server code.
I'll cross-file this in the publish repo

**Comment by flukeout** [comment]
Closing as Thimble works as intended. We can check up on expectations around this in our research.
