### ISSUE TITLE
The live-reload/preview feature has perfomance issues while typing long JS files

### ISSUE THREAD

**Issue by soapdog** [mozilla/thimble.webmaker.org#1286]
Thimble reloads/previews the project every couple keystrokes. When you're editing a JS file this leads to hundreds of cascading JS erros in the console which leads to performance degradation on the UI and more.

We could tweak that algorithm to refresh at a longer interval when editing JS or maybe even only refresh when switching files back to an HTML or pressing a play button.

I was working on https://d157rqmxrxj6ey.cloudfront.net/andregarzia/17163/ and had to type a 100+ JS file there and Thimble got very slow. It was due to errors exploding silently all over the place.

Anyone has any thought regarding that? How can we solve it?

**Comment by flukeout** [comment]
@soapdog You can disable Javascript in the gear menu in the editor. This will stop it from auto running.

![image](https://cloud.githubusercontent.com/assets/25212/11539163/8d10abc0-98da-11e5-9014-007b05062b33.png)

Let us know if this solves your problem.

The problem I anticipate is that when Javascript is disabled, it will be hard to test because you'll have to use the menu to turn it on, reload the preview, and then turn it back on again after for more editing.

**Comment by humphd** [comment]
I'm going to close this, since we have a way to deal with this, and let's file new bugs on improving this if needed.
