### ISSUE TITLE
Files don't save

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1287]
![auto-save](https://cloud.githubusercontent.com/assets/5816130/11544196/8f71bf38-990e-11e5-8872-a0d43c7c2795.gif)

It looks like changes to a file are either not being saved properly or are being overwritten with stale content when you navigate away from the page and back.

Tried doing a `Cmd+S` before navigating away, still didn't save.

**Comment by gideonthomas** [comment]
I tried waiting for 5 seconds, it still didn't save (unless that's the wrong autosave interval).

**Comment by humphd** [comment]
@gideonthomas we should probably prioritize this this week, if it's really true that we're losing data.

**Comment by humphd** [comment]
My suspicion here is that you have changes in the local filesystem, and pending operations (updates) to sync to the server.  Then, you hit refresh, and it downloads the tarball again for this project.  We have code to ignore files that have pending deletes, but we don't have a similar code path to ignore files that have pending updates: https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/editor/scripts/project/remote.js#L28-L41

What I think we want to do here is check to see if the file is supposed to be updated, and if so, use what's in the local filesystem already instead of overwriting with what's in the tarball.  I am unsure if I'll have time to get to this quickly tomorrow, but hopefully this is enough to get you started on it, @gideonthomas.

**Comment by gideonthomas** [comment]
So is it as simple as adding the extra changing the if condition in the code you linked from
```js
if(pendingPaths[path] === SYNC_OPERATION_DELETE)
```
to
```js
if(pendingPaths[path] === SYNC_OPERATION_DELETE || pendingPaths[path] === SYNC_OPERATION_UPDATE)
```
?

**Comment by humphd** [comment]
Try it please, it might be that simple.

On Dec 3, 2015 11:15 AM, Gideon Thomas <notifications@github.com> wrote:

So is it as simple as adding the extra changing the if condition in the code you linked from

if(pendingPaths[path] === SYNC_OPERATION_DELETE)

to

if(pendingPaths[path] === SYNC_OPERATION_DELETE || pendingPaths[path] === SYNC_OPERATION_UPDATE)

?

**Comment by sedge** [comment]
@gideonthomas seems pretty busy today, so I'll give this a try.
