### ISSUE TITLE
Develop technical approach to l10n

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.webmaker.org#1331]
Let's discuss our technical approach for localizing Brackets, Thimble and Publish.

**Comment by humphd** [comment]
We have bugs in a few places related to this, and therefore I'll probably repeat things, but let me outline some of the challenges I see.

Brackets core (upstream) is fully localized, and uses client-side dynamic rendering of strings from an included catalog via the https://github.com/requirejs/i18n plugin.  Bramble core is therefore *mostly* localized already, but lacks localization for things we've changed (there are at least a dozen, but it's not massive).  Localization in Brackets is discussed here: https://github.com/adobe/brackets/wiki/Localization

In addition to the core, a lot of what we do in Bramble is done via extensions.  Brackets extensions can also be localized, an example extension with docs on how to do it is here: https://github.com/adobe/brackets/tree/master/src/extensions/samples/LocalizationExample.

Brackets/Bramble picks the appropriate string catalog to load at runtime, and we probably need to somehow fold this into the `Bramble.init()` api instead of using the URL:

* https://github.com/humphd/brackets/blob/bramble/src/main.js#L67-L69
* https://github.com/humphd/brackets/blob/bramble/src/thirdparty/browser-appshell.js#L29-L30

We have some tech debt in here, because extensions need to be able to load the right strings, too.  I *think* that this is broken at the moment, because we ignore the `package.json` file for each extension, and I'm pretty sure it's where you are supposed to define your langs.  We might want to merge our extension strings in the core strings, or alter the way the locale is chosen for extensions in the core.  This needs some thought.

Thimble is also built on requirejs, so you could decide to use the same general approach.  I wouldn't choose to do it this way (I'd do server-side template rendering), but it would reduce the load on maintainers having to deal with so many different ways of working on locale code.

Similarly, Publish could do whatever is easiest (probably Hapi has some baked in way?).  What about login and id?  Are they already localized?  For all of these, there is also the need to provide ways for requests to specify language preferences.  Maybe that's done on a cookie, maybe directly via headers.  It needs to be thought about, since we don't bother with it now in publish, at least.

Localizing "Thimble" is therefore going to be really complicated, because it will involve quite a few different approaches, and no single string collection: having volunteers localizing with us will be a bit tricky because their work will have to get co-ordinated and combined by us or tools.  I don't know what's best here.  We also have to consider the fact that we inherit upstream translations from Brackets, and need to include those in whatever we do.

In the past, when localizing Webmaker tools, we got to the point where right-to-left languages became important.  We should consider whether we also want to tackle that--it has a significant cost on UI.  Also, I'm unclear if CodeMirror, which is the basis of Brackets, can do rtl.  Do we have a list of P1 locales?  The GA language stats might give one view on how to start.  However, maybe there are other locales that matter a lot, but are underrepresented currently due to the en-only nature of the UI?

These are some initial thoughts.  We can talk more in this bug, and in our kick off meeting next week.
