### ISSUE TITLE
Preview panel goes to top for every edit

### ISSUE THREAD

**Issue by ToonTalk** [mozilla/thimble.webmaker.org#447]
Makes it very difficult to use for pages that are long and require scrolling.

**Comment by humphd** [comment]
This is always going to be tricky.  The new Thimble prevents reloads from happening as often (we used to do it per-keystroke, and now we only do it if the top-level HTML tree is modified, but use DOM Diffs otherwise).

I'm going to close this because I have no idea how to make this better *and* still keep the preview in sync for all cases.  It's a trade off, for sure.  cc'ing @flukeout, so he can ponder for follow-up bugs.  Maybe if there was a way to turn-off auto-reload and let users do it manually when they wanted.
