### ISSUE TITLE
Implement Auto-Save

### ISSUE THREAD

**Issue by finnp** [mozilla/thimble.webmaker.org#480]
Right now when you reload, everthing is lost. Just saving everything to localStorage would be simple.

**Comment by humphd** [comment]
We're getting ready to integrate a large rewrite of the editor/preview code, which uses the Brackets code base, making what you describe above easily doable.  The new editor backend uses a full filesystem based on IndexedDB and/or WebSQL.

I'm going to morph this bug a bit so we can figure out the right mechanics for doing a full autosave implementation.  There are some issues to consider, including:
* what to do when you open Thimble and you have something saved (needs UX)
* which mechanism to use when triggering autosave.  This can be event based, timing based, etc.  There are tradeoffs for each.  We could also save "last-known-good" state, since we know when the page has errors and can't be rendered.
* what to do on publish with contents that are saved.

cc @gideonthomas, @sedge, @davidascher

**Comment by finnp** [comment]
I think it might be a good idea to save it to a local cache and only optionally really save it. So that when you reload your unsaved page, it will still show what you typed last, but it's not properly saved. Not completely sure about that though.

**Comment by humphd** [comment]
We're spec'ing this out atm, so I'll throw my notes here.  On the Thimble side (i.e., other parts of this will happen in Bramble), we need to do:

* in the proxied filesystem, we need to watch for calls that will dirty the filesystem, including `rename`, `unlink`, `writeFile`.  Probably we can ignore `mkdir` and `rmdir` for now, since we store whole files only on the server (dirs are just a naming convention in the path)
* As we write to the real `fs` instance, we also need to set an extended attribute on the project's root folder, indicating that a file has changes that haven't been saved to the server yet.
    * This process may repeat many times before we actually upload the file (e.g., multiple autosaves for a given file all result in the same thing: a "dirty" flag on the project root--we don't worry about versioning).
* At some point, whether in an automated or user-initiated way (we're still solving) we'll start uploading dirty files to the server:
    * get extended attribute on project root to find dirty file paths, `forEach`...
    * `readFile(dirtyFile)`, remove file path from dirty list
    * send file contents to server, wait on reply.  If `OK`, we're done; if `ERROR`, reset the dirty flag for this file in the project root's extended attribs.

**Comment by humphd** [comment]
This is done now, and shipped on staging.

**Comment by finnp** [comment]
Great!
