### ISSUE TITLE
Integrate new ID login system

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#497]
Integration of the [new ID.webmaker.org system](https://github.com/mozilla/id.webmaker.org) needs to be done.

**Comment by humphd** [comment]
adding @simonwex, @davidascher, @jbuck, @toolness, @cadecairos  

We'll do the work for this, but I'd love some guidance on how we go about making this happen.  @toolness, I hear you recently did something like this on the new Teach site?  Can you point us at commits or bugs that might help?

Also, I assume that we'll need to patch the old + new Thimble to use this new system, which is to say, I assume you are going to end-of-life the old login stuff?  Can someone confirm this?

**Comment by toolness** [comment]
Sure! The way we do it w/ the new Teach site is actually a bit [odd](https://github.com/mozilla/teach.webmaker.org/issues/576) because of the fact that teach.mozilla.org itself has no actual back-end (it's just static files deployed to S3).

It might actually be easier for me to just update my [webmaker-connect-node-example](https://github.com/toolness/webmaker-connect-node-example) to work with id.webmaker.org, so that you folks and anyone else who wants to integrate with id.wm.o has a "hello world"-style app to use as reference. Would that be helpful?

Also, the documentation at https://github.com/mozilla/id.webmaker.org/blob/develop/docs/oauth.md was really, really useful to me while doing the integration work.

**Comment by sedge** [comment]
@toolness  A reference app would be fantastic.

I'm reading through `oauth.md` right now and it might be enough, but I doubt we'll be the only ones who could benefit from a full example of this.

**Comment by humphd** [comment]
@toolness since we have a node app, do you think we should do it that way?  I assume 'yes' but you tell me.

**Comment by toolness** [comment]
> @toolness since we have a node app, do you think we should do it that way? I assume 'yes' but you tell me.

Er sorry, which way are you referring to when you say "that way"?

Another alternative would be to look at any example app that uses [GitHub login](https://developer.github.com/v3/oauth/); it's OAuth2 as well, so aside from the specific URL paths it uses, it's extremely similar to id.wm.o. The only unfortunate thing about id.wm.o right now is that there's no front-end devs can use to register their app like there is with [GitHub](https://github.com/settings/applications/new), so you'll have to ask jbuck to add you manually.

The only "weird" thing about id.wm.o compared to other OAuth2 providers is actually log*out*, not login. As discussed in https://github.com/mozilla/id.webmaker.org/issues/119#issuecomment-89008358, it doesn't make a lot of sense *not* to log users out of id.wm.o when they log out of your app, so there's a logout flow that parallels the login flow. This differs from other OAuth2 providers like GitHub, where there's no logout flow, and users are expected to log out of *two* websites if they want to "completely" log out--the OAuth2 app and the OAuth2 provider (e.g. GitHub itself).

**Comment by sedge** [comment]
I've finished my initial round of research and determined the first steps to getting this working on thimble:

Server-side
* [ ] Adjust user bar rendering to pass info from ID vs Login (server side, routes/inex.js)
* [ ] Add rendering to sign-in link url to include client_id + roles
* [ ] Add /callback route
* [ ] Change auth checks in server code and API code, at middleware level
* [ ] Render user info for user bar if auth token exists

Front-end
* [ ] Develop front end generation of state string with hash and add to the cookie

**Comment by sedge** [comment]
I'm going to be storing each user's oauth token as an encrypted string attached to the cookie session. This isn't my first choice, since AFAIK exposing the token in any form is bad practice.

I figure for MVP this is fine though. The other solution I can think of would use some sort of DB (redis maybe?) to track who is signed in and is significantly more complicated.

@jbuck @cadecairos Any thoughts on this?

**Comment by jbuck** [comment]
Why wouldn't that be your first choice? It's a secure way to store data and it doesn't require an attached database.

**Comment by sedge** [comment]
haha paranoia? I'm instinctively uncomfortable with exposing the token, even though it would be encrypted. Judging from your reaction I must be over thinking it.

**Comment by sedge** [comment]
@jbuck @cadecairos @simonwex Do we need to adapt legacy thimble to use ID as well?

**Comment by jbuck** [comment]
@sedge nah

**Comment by cadecairos** [comment]
So login.wmo and it's DB will stay up for as long as we maintain the app?

**Comment by jbuck** [comment]
@cadecairos yes, but we won't be maintaining thimble-classic for long, I think

**Comment by sedge** [comment]
@jbuck I've landed our patch, but the credentials (client_id specifically) are being rejected by `id.webmaker.org`. Can you send me new ones?

**Comment by sedge** [comment]
Done! Live on bramble.mofostaging.net
