### ISSUE TITLE
Create user/contributor engagement strategy

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#501]
We need to teach our contributors/users that the thimble project is alive and under active development.

This could include:

* Blogging
* Leveraging mailing lists
* A user testing strategy

**Comment by humphd** [comment]
Moving out of this milestone, while @hannahkane is away.

**Comment by hannahkane** [comment]
Update on this:
 * User testing is in place. Two rounds on usertesting.com complete, with a third scheduled for the upcoming heartbeat.
 * Additionally, about half a dozen experienced Thimble users have been engaged in testing on staging site
 * We have not blogged since the initial announcement and follow-up post, but a comms plan is in development: https://docs.google.com/document/d/1axAmOwVVdvW_mwy9IfnW8sJlaJ4m6kDd4MHVzEMSboc/edit

**Comment by hannahkane** [comment]
Some add'l things to work on (drawn from @acabunoc's excellent article: https://www.mozillascience.org/seven-steps-to-building-community-around-your-open-source-project):
 - [ ] Make sure https://github.com/mozilla/thimble.webmaker.org/blob/master/README.md is up-to-date
 - [ ] Identify some Good First Bugs and label them as such
 - [ ] Create and publish contributor guidelines 
 - [ ] Publish a roadmap

**Comment by acabunoc** [comment]
👌
