### ISSUE TITLE
webmaker-i18n language routing stripping query string

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#525]
How to re-create:
1. Go to https://bramble.mofostaging.net/?enableExtensions=ImageUrlCodeHints,CodeFolding
2. Change languages using the top right dialog

I suspect that webmaker-i18n submodule is stripping the query string when the UI is used to select the language. This means that the query is lost and therefore not passed on to Brackets.

re: @alicoding

**Comment by alicoding** [comment]
Yeah this is definitely a webmaker-i18n bug. I've tested it on webmaker.org as well to confirm that. We're just not keeping/checking the state of query string at all, so we need to add this.

I'm at the conference this week, but will find a time to do this otherwise I can help review a PR if you can come up with something or if you found the issue.

**Comment by humphd** [comment]
The only place it modifies the `req.url` is here https://github.com/humphd/node-webmaker-i18n/blob/master/i18n.js#L246. I'd take a look at whether it's happening here.

**Comment by JordanTheriault** [comment]
Narrowing it down, this issue is actually in [webmaker-language-picker](https://github.com/mozilla/webmaker-language-picker). Further investigating now.

**Comment by JordanTheriault** [comment]
Fixed in [webmaker-language-picker#17](https://github.com/mozilla/webmaker-language-picker/pull/17)

**Comment by JordanTheriault** [comment]
Fix has been merged upstream, and version changed via #545
