### ISSUE TITLE
UX exploration for exposing files in a Project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#527]
We need to figure out how we'll handle files and projects. Specifically:
* How does a user toggle or expose the file view?
* How are files in a project displayed?
* How are files added, deleted and renamed?
  * Can we just lean on native Brackets functionality here?
* How does a user open one of their existing projects?
* How does a user save & name their current project?
* How does a user delete their projects?

**Comment by sedge** [comment]
@flukeout I'd like to add a consideration, which is remixing.

* How does a user choose a project to remix?

Because these apps are going to become complicated, we figured we'd need a different solution from permanent UI with a remix button in published projects. Whichever way we go, we'll need a design.

Our MVP was planned to be a dialog with a list of users, and a list of their projects. Clicking one would remix it into the authenticated user's tree as a new project with the same name.

**Comment by flukeout** [comment]
@sedge Indeed! That MVP idea sounds pretty good, we definitely need a cool way to browse and explore the projects. I think we'll need to offer a good preview mode for the projects, otherwise the remix action won't be as compelling. Have you guys thought about other ways to sort / organize the projects?

**Comment by hannahkane** [comment]
The way to browse and explore the projects is the gallery functionality we talked about, right? 

I'd be interested to do some user research to understand users' mental models. Do they have something specific they want to search for? Do they want to browse based on skill level or some other facet? Do they want to browse a list of topic categories? I'd love to get a sense of the real use cases for when people want to remix.

**Comment by flukeout** [comment]
Just throwing something really preliminary down as I'm starting to tackle this. Let's chat in the stand tomorrow.

![image](https://cloud.githubusercontent.com/assets/25212/7928897/12b0cf7c-08ac-11e5-9acd-09a5d025a99c.png)

This mockup starts to tackle some of the issues I outlined at the top of the issue, but also raises a few questions.
* Which file operations do we want to support?
  * Brackets has a ton of stuff available if you right-click a file in the file view, which of these do we feel are important?
* How opinionated are we about file types that you can edit? Do we just support the three types pictured?
  * Need a way to import files from the file system
  * Need a way to import images, select from computer, drag into sidebar?
* Do we allow folders?

Anyway, I'm just rambling a bit as I wrap my head around this. Let's chat tomorrow and define scope!

**Comment by humphd** [comment]
One caution I want to make as we get into this: redoing the Brackets UI is outside the scope of our work.  I think we need to focus mainly on the UI *around* Brackets vs within it, since doing major surgery on their UI is going to get us into the weeds quickly (we don't have the time or resources, and it gets hard quickly).  That said, we can and should be doing things like styling/themes, removing UI that doesn't make sense for us, adding things within the context of their existing UI where we can, and doing light additions where we can.

To respond to some of your questions:
* I think we can remove `Show in Finder`, `Find in...`, and `Replace in...`, but `New File`, `New Folder`, `Rename`, and `Delete` all seem like logical things to include.  The beginner mode doesn't need to expose these (or the filesystem at all), but after that you'll quickly start needing/wanting these if you work with multiple files.
* Regarding supported file types.  We did a pass at this, and stripped the Brackets language support down to what we thought was potentially useful for working with the web, see https://github.com/humphd/brackets/blob/bramble/src/language/languages.json.  We can refine this further, but I think we should be able to cope with all these.
* We've implemented drag-and-drop from local computer to Bramble--you can drop any number of files onto the editor or treeview, and it will write them into your filesystem and open them.  If they are of an unknown type (e.g., `program.exe`) or are larger than 3M (this number is arbitrary, and easily changed if you want) we'll show an error saying we couldn't include that file.
* Regarding folders, I think so.  Why not?  We don't need to force you to use them, but we shouldn't stop you.  To do so creates an unnecessary ceiling for users.  If you want to hide that in some mode(s), we can do that.

**Comment by flukeout** [comment]
Here's a quick update that tackles a few issues:
* Shows collapsed & expanded state
* Adds "Project Title" UI in place of "EDITOR title", which we haven't addressed yet but will be important for auto-saving projects
* Updated "Rename & Delete" functionality that mimics what Brackets already does and adapted for Desktop & Tablet
* Expanded the "New File" dialog to include picking from local files

**Note** - still mostly UX at this point, let's leave the fine-grained UI feedback for Redpen

**Missing Features**
* For now, left off **Folders** on this pass, do we have a strong reason to tackle that UX / UI right now?
  * We could automatically put all images into an auto-generated "images" folder and remove it when there are none

Which options from this menu do we want to keep?
![image](https://cloud.githubusercontent.com/assets/25212/7944233/55449856-091e-11e5-843d-84de14057d97.png)


![image](https://cloud.githubusercontent.com/assets/25212/7944093/84331044-091d-11e5-88ac-8661a74656c2.png)

**Comment by humphd** [comment]
* The collapse and expand tray icon is good.  I wonder if it can go above  the editor/treeview (i.e., sort of up with undo/redo, on that level)?
* I like the edit-in-place project name, but I think it should go up in the Green header vs. in the editor, so that we don't have to a) hack so much of Brackts' UI to make it happen; b) not lose more vertical editor room to support it.
* For the drop-down in the file view, would it add that to the currently selected file?
* I like the idea of the "New file" button at the bottom of the tree view, but not the look.  I think a + sign or the like might be better?  I don't know, it just looks bulky, and really stands out.  It might even be better to move that up to the top, too.

In terms of what's in those menus, I don't think we need anything else right now.

**Comment by flukeout** [comment]
@humphd The edit-in-place area is the same area that will have all the font size / redo undo stuff, so it's definitely not part of the brackets editor. My thoughts were that everything in those bars is ours, and Brackets only begins under the separation with the little shadow.

Agreed on bulk of **New File** action - will tweak UI in subsequent phases.

**Comment by humphd** [comment]
Cool, we're thinking the same thing then, +1

**Comment by hannahkane** [comment]
+1 to all of the above, including the fact that I don't think we need anything else from those menus yet.

**Comment by flukeout** [comment]
Latest UI work is in a section of this redpen -> https://redpen.io/wo889e2e3abea83b34

**Comment by flukeout** [comment]
I've renamed this issue to reference exposing files in a project only. I'm moving the project exploration view work to #549

**Comment by flukeout** [comment]
@humphd Are we good to close this issue?
