### ISSUE TITLE
Alternatives to multiple file editing

### ISSUE THREAD

**Issue by toolness** [mozilla/thimble.webmaker.org#540]
Hey!

I was talking to @simonwex after our Thimble meeting today and raised a few concerns about our multi-file editing approach.

In short, I want to make sure that multi-file editing is the simplest possible solution that solves our actual user need.

For example, in my (albeit limited) experience interacting with learners, one of the biggest problems with only having a single HTML page to edit is that it means you quickly have at least 2 different languages in the same file (HTML and CSS, possibly JS too). Figuring out exactly where one language ends and another begins can be *really* hard for beginners. However, the solution here doesn't need to be multiple arbitrary files--it could just be having separate document panes for JS and CSS, which is actually why a number of organizations I know prefer [JS Bin](http://jsbin.com/) over Thimble. It solves the user problem (in this one particular situation) in the simplest possible way.

In a similar vein, one of the biggest motivators I've heard for supporting multiple files is that users want to be able to upload images. However, images on websites have some salient characteristics that make them fairly different from other files: for instance, unless we embed an image editor into Thimble, they're not going to change often, if ever. In fact, having a separate "images" or "media" pane in Thimble could be really nice in some ways--it'd potentially be more intuitive to a user who has no idea what a "directory" is, for instance--and could also simplify our data model enough that we're less constrained in some of our implementation options. And images are also alot more identifiable by thumbnail than filename.

Anyhow, I guess I just wanted to make sure we were addressing the immediate user needs here, rather than jumping directly to the solution we assume (as developers ourselves) is the most ideal. @flukeout, if you have any time to mock up UX or even low-fidelity wireframes for solutions that *don't* assume multiple files while still solving the major user needs, I think that could be particularly useful--even if we still end up going with mutliple files, at least we'll know we're doing it because it's *actually* the best solution for the problem.

(On the other hand, I'm also new to this whole debate, so maybe you folks *have* already considered alternatives to multiple files. In which case, that's awesome, sorry to waste your time :grin: )

**Comment by thisandagain** [comment]
Major :+1: on this @toolness .

In my experience teaching (albeit this is to kids and I'm *more* than a little biased) I've similarly preferred using JSBin because of the simplicity of separating HTML / CSS / JS but without jumping completely into needing to explain a filesystem. I think it's a concept that so many of us take for granted (particularly those of us that are comfortable on CLI) but it is often difficult to on-board new learners into. I know we touched on this concern a little bit with MakeDrive but I'd similarly like to see us spend some design time on evaluating the range of solutions between "single file" and "in-browser file system".

**Comment by Pomax** [comment]
in terms of the 'where do these things begin/end' I always thought it would be useful to have an editor that effectively did inline linking, so that it even though things are separate files, that is simply an irrelevant fact until I want to learn more about it.  CSS and script elements could just show an expanded box that makes it super obvious that it's *not* HTML and physically point to another file, but letting me edit without changing contexts. It's one things I don't like about jsbin and jsfiddle for instance: even though the panes are handy for "separation of concern", there's only one script, and one style pane. I just end up writing a mess of "Everything's crazy together". Something that "writes the right thing for me" while keeping everything organized as files so I can switch to a "real editor view" at some later point in my life would be nice. Single page *presentation*, structured such that it's basically jsbin without the "one pane per context" restriction, and then underwater *encoded* as multiple files in the user's store.

**Comment by flukeout** [comment]
@toolness Good thoughts. As far as mocking up non-multiple-file solutions, I think we can pretty much pick from any of JS Bin, JS Fiddle or CodePen. They all do that in slightly different ways and I think they're all successful for slightly different reasons.

I think it boils down to what the goal of the learning activity or process is. If it's about showing the simplest possible way how javascript and HTML can interact, then a multi-pane approach might be the best. The muti-pane approach strips out a lot of the context in which a web page lives, though, so there is a sacrifice. If we're able to streamline the multi-file approach, there's learning happening there just through the awareness that, hey.. web pages are composed of a bunch of files!

We can do some smart auto-linking between the pages to ease that friction, and start people off in a project that already has all the linkages set up.

Anyway, some rambling there. I think the bigger issue is settling on what we're attempting to teach, which I definitely can't answer alone. I'm in favor of multi-files because it mirrors more closely how things are actually done on the web.

**Comment by humphd** [comment]
We're pretty far down the multi-file path now, this would be a pivot.  Closing.  Perhaps this thinking can go into another tool or project down the road.
