### ISSUE TITLE
Figure out starting content for editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#541]
What do we want our starting content to be a blank/new make? Currently, we have a ```p``` tag with a line of content, but I think we can do better. We can divide this into beginner and multi-file modes.

**Beginner**
This is the single page mode without a file browser and has...
* A couple of tags with content, maybe an ```h1``` and a ```p```
* A ```style``` tag in the ```head``` with...
  * Some basic styles for the text elements (font-size, color and font-family)
  * A background color for the ```body```

**Advanced**
Multi-file project with...
* index.html - same markup as beginner mode, but with an additional ```button``` element
  * *style.css* and *script.js* are linked in the ```head``` tag
* style.css - some basic styles (like listed above) for the elements on the index page
* script.js - a very basic code example, like a click handler for the ```button```

This will give people something to tinker with immediately.
@hannahkane @cassiemc what do you guys think about something like this? Have we experimented with different starting content before?

We could add an element of chaos to this too, and pick a different background-color for the ```body``` every time you start a new project.

**Comment by hannahkane** [comment]
My comments are a bit outside the scope of this ticket, but it's difficult to talk about this initial experience without also talking about the experience around it.

Short answer: I think what you've proposed for beginner and advanced modes are fantastic. Like!

Longer answer: 
 * your suggestion implies that we can offer different starting points for these two different modes, perhaps by including the mode in the query string, as discussed earlier, right? That makes me wonder how the user can switch modes once they're in it. Like, if I end up on the Advanced mode, and I'm overwhelmed, can I become aware of Beginner mode and how to get there?
 * For many users, I imagine the right first experience will be to remix. Sometimes, there's nothing worse than being faced with a blank page! (Or even a blank page with a button on it.) Again, this is probably out of scope for this ticket, but maybe we should think about exposing pathways to existing content.

**Comment by humphd** [comment]
Some technical issues to be aware of and some thoughts:
* Because we auto-preview HTML files when they are created, they must be valid HTML, which means we can't ever create a totally blank HTML file.  Luke's point above about having default content fits with this, but just for future discussions regarding clicking "New" or the like.
* Brackets has a bug where it needs at least one CSS file to exist somewhere in the project.  We can hide this fact for the beginner case (e.g., we don't have to show the files at all), but it should be there.  I think our default CSS and even JavaScript file are useful to ponder.  What about having a default image file that's always in the filesystem too?  Then you have everything you'd need.  Again, we don't have to show these things necessarily, but they can be there to be discovered or revealed later on.
* I wonder if the beginner mode should really have CSS at all.  Why not just pure HTML?  CSS seems like step 2 vs. something you do right away.  Same for JS.  This also points at the fact that we could do any number of modes: html-only, html+css, html+css+js, etc.  The beginner mode might be html-only, for example.
* I like the idea of improving the first page HTML you get so it is a bit more engaging, as long as we don't make it into something that's going to overwhelm people right away.  ```<html><p>Hello web!</p></html>``` is also a valid HTML file, for example :)
* I also agree that most people probably won't start from zero, but open some existing project and make changes.  That said, we can support as many modes as we think is useful (via URL maybe with `?mode=xyz) and add UI for the ones we want to surface as first-order, and can be easily switched between.

**Comment by jgmac1106** [comment]
@hannahkane is right. Almost everyone starts with a remixof some kind. This is also bakek into the Mozilla Learning pedagogy IMO. 

So it may have just as much to do with creating well scaffolded makes for the learners to remix rather than the stsrting copy. 

Today was my first time playing with Beta. I loved how opening and closing tags highlighted together. 

I would leave the start screen as is rather than adding in complexity. 

In my experience learning and teaching with Thimble users want to add a hyperlink, add a pic,  change background color. 

So I think the entry points to beginner and advanced modes might be the remix folks select to start with.

**Comment by flukeout** [comment]
Good thoughts - here's an interim solution.

**For now**
* When creating a **New** project from inside the editor we offer a choice...
  * Simple 1-file project (Beginner Mode above)
  * Advanced 3-file project (Advanced Mode above)
* We can offer this in a modal that explains the difference, like this...
* The editor UI or UX doesn't change, just the number and types of starting files and their content

Rough take on this approach...
![image](https://cloud.githubusercontent.com/assets/25212/8138613/4a5b994a-1101-11e5-8b58-b6df91eeb050.png)


**For later**
* We add a way that lets users remix other projects as a starting point as well
* This way they can filter by topic, category, etc...

**Comment by flukeout** [comment]
Update - we'll be starting with just one type of blank new project and exploring ways to reveal, or level-up the author in another issue.

**Comment by flukeout** [comment]
```
<html>
  <head>
    <title>Your awesome page</title>
  </head>
  <body>
    <h1>Welcome to Thimble!</h1>
    <p>Make something awesome with the web!</p>
  </body>
</html>
```

**Comment by jgmac1106** [comment]
+1 I like the addition of the h1 tag to differentiate.

**Comment by hannahkane** [comment]
Thanks, @flukeout. Just want to make sure I understand. Is the behavior different when a user clicks "New project" based on which mode they're in?

**Comment by flukeout** [comment]
@hannahkane No, the behavior is the same. The way I'm thinking about it right now, is that there is no difference between simple and advanced. You can remix an 'advanced' version of a starter project to get the extra files and different starting point. One cool thing we can do is that if you start a new project or remix a project with just one file, we start the file tray minimized. If you open or remix a project with more than one file, then we reveal the file tray at the start by default. What are your reactions to that?

**Comment by hannahkane** [comment]
I like the file tray being hidden/closed based on the number of files. That makes sense.

So, there's no "advanced" version of the New Project action, but we do offer an advanced starting point via, say, a similarly mostly empty but multi-file project that users can find somewhere (the gallery?) - is that right?

**Comment by flukeout** [comment]
@hannahkane Yeah, that was what I was thinking.

**Comment by hannahkane** [comment]
OK, perfect. I understand, and I think that works. :)

**Comment by humphd** [comment]
It's interesting to look at what https://atom.io/ does here:

![atom](https://cloud.githubusercontent.com/assets/427398/8393636/93d4e9be-1ce6-11e5-8e60-01a2b602ce93.png)

If we agree that most people are going to enter Thimble via a remix action, then it might make sense to *also* have a first-run experience that's different, and allows you to explore and get to know how the tool works.

**Comment by hannahkane** [comment]
Just making a note here that @flukeout and I also talked about having a screencast tour as part of the First Time Here experience.

**Comment by flukeout** [comment]
So, we have a couple of starting points to consider

**1. Blank project from Scratch**
This is when a user hits New Project in the Thimble editor or presses the white button on the homepage. I think this one can be a little more complicated, so I suggest we roll with something like this...
http://bramble-staging.s3-website-us-east-1.amazonaws.com/7/starting-project/

This contains
* HTML file with the following markup
```
<html>
  <head>
    <title>Built with Thimble</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <h1>Welcome to Thimble</h1>
    <p>Make something awesome with the web!</p>
  </body>
</html>
```
* A style.css file with the following content
```
body {
  font-family: "Open Sans", sans-serif;
}
```

**2. New HTML file added in-project**
When a user adds an HTML file via the file dialog in Thimble, we should provide a more basic HTML template. I propose the following...
```
<html>
  <head>
    <title>Built with Thimble</title>
  </head>
  <body>
  </body>
</html>
```

**Comment by hannahkane** [comment]
Thanks, @flukeout.

I worry that the nearly blank page is scary for newbies. 

I wonder if it would be useful to include in the html file of the new blank project either a pathway to remix and/or a pathway to get help (e.g. "Not sure what to make? Check out these sample projects"). 

I realize that would probably be annoying to see every time you start a new file from scratch. Maybe it only shows up once, if you're authenticated? Or maybe there's a way for the user to indicate they never want to see those prompts again?

Curious to know what @jgmac1106 thinks. :)

**Comment by flukeout** [comment]
@hannahkane We're already going to have a bunch of entry points to remix existing content from the homepage and eventual gallery, so I don't think it's as important to put links and content into the default blank project. We don't want it to be a pain to erase everything before you start your work, either.

That said, curious about @jgmac1106's thoughts.

**Comment by jgmac1106** [comment]
This seems related to #570 in terms of entry points. 

The majority of people begin through remix so I see no need to have more content than what is proposed for those who hit blank projects. 

How will the FAQ on help change? We could add a link there.

**Comment by hannahkane** [comment]
OK, if others aren't concerned about the blank page, then I won't worry about it. :)

There's a ticket to update the FAQ here: #567, in case anyone wants to jump in on that

**Comment by hannahkane** [comment]
@flukeout - I'm thinking we need to move this ticket to MVP? Or perhaps open a new one with the solution we agreed upon above. We don't want to launch with the Keep Calm project as the default, right? Do you need the Keep Calm default to continue to exist for the final round of user testing?

**Comment by flukeout** [comment]
Published version of the starting content is here
https://d157rqmxrxj6ey.cloudfront.net/flukeout/139/

The blank project contains 2 files
* An *index.html* file that contains...
```
<html>
  <head>
    <title>Built with Thimble</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <h1>Welcome to Thimble</h1>
    <p>Make something awesome with the web!</p>
  </body>
</html>
```
* A *style.css* file with the following content
```
body {
  font-family: "Open Sans", sans-serif;
}
```

**Comment by humphd** [comment]
@sedge, I need the `env` for stating/prod updated to switch the default project: https://github.com/mozilla/thimble.webmaker.org/pull/929/files#diff-45473cb0daa25d5231f105558b5b7226R136, and then this can be closed (I've already landed the code changes).

**Comment by sedge** [comment]
This is done. Closing
