### ISSUE TITLE
UX for Thimble homepage page & Gallery

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#555]
Pasting from [the related planning ticket](https://github.com/MozillaFoundation/plan/issues/477).

* Design a Thimble landing page that provides context for new users
* Landing page will prominently feature galleries - both public and personal
* Design solution for navigating between landing page and project editor

**Comment by flukeout** [comment]
Starting thoughts
* As a start, show a list of the latest published projects sorted by newest first

Each projects includes
* Project preview
* Method to view the project 
* Remixing the project can happen once the project is viewed  
* Author name <- what do we link to?
* Project name

**Comment by hannahkane** [comment]
This is a good list. I'd add the ability to search the projects, though I'm not sure what data we're indexing—title, author, tags?

I think the Author name might link to a filtered view of other publicly-viewable projects by that author.

**Comment by flukeout** [comment]
@hannahkane Thanks! I've updated the list.

**Comment by flukeout** [comment]
Added notes from @jgmac1106...

As a teacher, I would also like to search the gallery by clear technical objectives

* formatting text with css
* add an image

This would require those designing makes for remix to somehow list these objectives but it would be a useful feature when trying to create a scaffolded curriculum.

**Comment by flukeout** [comment]
We need to do some work to define the audience and their motivations to make this successful. As an exercise, I'll assume a basic split it what someone arriving here might be looking for...

* Show me something cool
  * Show a list of the best newest projects
    * Most likes
    * Most remixes
* Teach me something specific
  * Show a list of categories or skills that I can use to find a project that teaches me something specific
    * How to use images
    * How to set CSS properties
    * How to write a Javascript loop
    * etc.
* Show me my stuff
  * An easy way to get to what I was working on last

**Comment by hannahkane** [comment]
This is really helpful.

I really like the breakdown of cool stuff vs. learn something specific.  I'm not 100% clear on the mental model for the "Cool stuff" — are they looking for something cool to remix, or are they looking at something for the sake of it being cool? I ask because it seems like that might affect copy, the prominence of the remix feature, and maybe even how we decide what's "cool."

The "Help, I'm lost" paradigm is the least clear to me. Is that something we'd expect people to visit more than once? Wondering if a "First Time Here?" mental model might be useful. That could achieve the "explain what Thimble is" part as well as include something tour-like for first time visitors.

Also wondering about the audience, since we have two—the educator audience might want to know how to use this to teach others, while the "end learner" audience might want to just get started. Should we address both audiences?

**Comment by hannahkane** [comment]
Summary of conversation @flukeout and I just had:
 * purpose of "Cool stuff" is inspiration + incentive/reward for makers; looking at existing gallery, would probably need to prioritize freshness, since the current gallery showcases makes with lots of likes, even if the activity is from awhile ago. Concern about lack of content strategy for this part.
 * agreed that "Learn something" should be the primary mental model; and could feature carefully curated content in different learning categories (e.g. "cool things people are doing with fonts" or "animation", etc.). Could also feature resources specifically for educators (i.e. teaching kits). Would love help from Learning Networks team in fleshing that out. cc @ldecoursy @chrislarry33 @amirad @omnignorant
 * @flukeout will continue iterating on the landing page, with perhaps less of an emphasis on a gallery (at least until we have a clearer content strategy)

@flukeout, does ^ match what we talked about?

**Comment by flukeout** [comment]
@hannahkane That sounds great - here's another set of mockups that addresses some of these points...

https://redpen.io/pa1a1b8f2fec79f629

**Comment by flukeout** [comment]
Closing this as our initial scope is way smaller and moving new work to #655
