### ISSUE TITLE
Implement remix functionality on thimble

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#570]
Educators often rely on sending students to a Thimble make and asking them to remix it by hitting the Remix button in the Details bar - See #557 for more details.

Picking up from #562 

What will it take to implement a slightly simpler version of this bar than we have now?

**Here's how it might look**
![image](https://cloud.githubusercontent.com/assets/25212/8218692/66528428-14f9-11e5-80fa-d68a1fee4eb7.png)

**Features**
* Remix Button!
  * Opens Thimble editor with a Remix of the current project
* Thimble Logo that links to the Thimble homepage
* Project Details
  * Author - linked to author's gallery
  * Name
  * Published date
* Less prominent and fixed to top of page when project is scrolled

*Note - Thimble homepage and user gallery are still not fully designed.*

**What it doesn't do**
* Have any features that rely or know about who the viewer is, and if they're signed in or not
  * This eliminates security concerns that would increase the complexity of the dev effort
  * We will have to drop the ":heart: Like" feature

**Implementation Ideas**
* When publishing we bundle a javascript file with the source that injects the necessary code
  * We can strip or hide this from the Editor and Editor Preview
* ...?

@humphd Can you take a stab at evaluating the dev effort and timeline for this feature?

cc @hannahkane

**Comment by humphd** [comment]
Doing this is going to involve at least the following:
* creating some way for getting all the necessary info we need to put in the page.  Perhaps we can do this statically on publish
* figuring out how to make the UI elements work in most pages (I say "most" because I don't think we can almost make it work, since user's can write CSS to hide or otherwise mess with it).
* Having publish do 2 things: 1) write a pristine snapshot copy of the files in a project into the database; 2) inject the script/UI bits we need and copy that to some other location.  That way when you click "remix" we can just pull the snapshot files out of the database for the given project, and put them in the user's project table.
* teach Thimble how to deal with query params that indicate we're remixing a project.  Since we can't support authenticated access in the published page, we have to kick off the remix action client side when Thimble opens.  Perhaps this means we give it `?remixProjectID=1234` and it sends a request to Thimble for the files in that project.  It would need to work for the unauthenticated user flow, too, so we couldn't just do a copy on the server side, since we don't necessarily know who the user is yet.

There's a heartbeat's worth of work in here, imho.

cc @jbuck, @Pomax (who might have historic perspective on this, since we've been here before) and @ashleygwilliams, @gideonthomas, @sedge (since this will affect the thimble/publish servers).

**Comment by hannahkane** [comment]
Putting this into the next heartbeat. Goal is to come to an agreement on an MVP.

**Comment by flukeout** [comment]
Here's the MVP version:
http://flukeout.github.io/thimble-home/stay-calm/

**Comment by hannahkane** [comment]
I like how nice and simple this is, and the Remix button sticking around as you scroll is cool.

**Comment by sedge** [comment]
Looks great! Question: What would happen if someone clicked the user's name?

**Comment by gideonthomas** [comment]
Fixed in 3e55c4eaea678c5a65171ea65bfad79fcb323822
