### ISSUE TITLE
Figure out how to manage various startup states and prevent data loss

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#631]
I've got a project that consists of an index.html file with a linked style.css file. After making some edits, I switch back and forth between the files, and the green header says "Auto Saving..." for a bit. When the saving message goes away, I refresh the browser and the changes do not persist.

**Comment by humphd** [comment]
This isn't autosaving not working, but rather Thimble overwriting the saved `index.html` on startup.  We need to figure out how to deal with various states on startup.  I can think of at least the following possible states:
* first time ever loading Thimble, nothing in filesystem and we need to generate something
* second, third, ..., nth visit to Thimble, something in filesystem which may or may not be what the user wants now.
* in the middle of working on code, browser closes/crashes and user reloads to continue, something in the filesystem and the user wants to pick up exactly where she was
* user has previously been working on code, it was saved to browser filesystem (all data is available locally in browser), but they lost network or closed the browser before it got sent to the server.  The user probably expects us to finish syncing the data to the server.
* the user was been working on their "My Project" project for a few days, alternating between their laptop and desktop.  They expect to be able to open their work and keep going on either computer, and not have old files overwrite newer ones when Thimble is opened on the new machine.

I don't know if it's possible to automatically handle all of the cases above, since a number of them conflict.  I wonder if what's really needed here are some checks on startup that potentially prompt the user for a decision.  Before we destroy data (which is what is happening in your "`index.html` gets overwritten" case above), we should prompt the user or find some way to automatically make the right decision.

**Comment by flukeout** [comment]
Here's are some steps that seem like a bug to me, and relate the the second bullet point.

* Load up a previously saved & named project
* Edit some HTML & see the changes reflected in the preview window
* "Saving..." indicator doesn't appear after I make changes
* Open the style file, then open the index.html file, this triggers the "Saving..." indicator, so I assume the changes are saved
* Reload the browser
* Get to the Project List page
* Choose the same project
* The HTML changes aren't there anymore...

Happy to demonstrate over Vidyo when you have a sec, but that just seems like a bug.

**Comment by gideonthomas** [comment]
@flukeout can you confirm that this is still an issue on staging? I think our current cache patch should have fixed this!

**Comment by flukeout** [comment]
@gideonthomas All seems well now - the scenario I outlined above is no longer happening - closing.
