### ISSUE TITLE
Mobile preview doesn't match desktop preview right after making a style change

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#633]
I made a change in a linked CSS file to make the background pink, it appears correctly in the desktop preview

![image](https://cloud.githubusercontent.com/assets/25212/8436439/3ede5750-1f0d-11e5-9de4-4b2a6e815a9c.png)

Then I toggle to the mobile preview, and the background color is still showing as green...

![image](https://cloud.githubusercontent.com/assets/25212/8436445/45a0cd20-1f0d-11e5-9dad-01c4e64d664a.png)

**Comment by gideonthomas** [comment]
@humphd so I think I know what the issue is. This is a general reload problem. We make changes to the css (and don't save), it gets propagated to the preview (I think only a new temporary blob url is generated) and we see the change. But when we refresh the preview, the change disappears because it uses the actual cached blob url.

**Comment by humphd** [comment]
Hilariously, this is YET ANOTHER CACHE BUG, this time in our internal web server/browser :)  The CSS updates are being sent inline via `postMessage` and applied via a secondary `<style>` that overrides the external `<link>`.  We'll have to force the `HTMLRewriter` to not use cached blob URLs in this case somehow.  I'll work on this.

**Comment by humphd** [comment]
This is going to involve doing something like the LiveServer, and teaching BlobUtils about CSS Live Docs.  Basically, we can't assume that CSS resources are only updated on disk write, but could be open in an editor and have changes.
