### ISSUE TITLE
Edits to a CSS file cause the file tray to 'deselect' the CSS file I'm editing

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#637]
I open a CSS file - the opened file is highlighted in the file tray...
![image](https://cloud.githubusercontent.com/assets/25212/8437564/acd98f48-1f14-11e5-91cf-7b76cd71ef8e.png)

As soon as I make an edit in the file, the opened file is no longer highlighted in the file tray...
![image](https://cloud.githubusercontent.com/assets/25212/8437595/d99e5ebe-1f14-11e5-9da2-343a3adc1097.png)

This seems to happen only on the first time I edit the file. When I open another file, return to this one and edit it some more, it stays selected in the file tray. Doesn't happen to the index.html file.

**Comment by humphd** [comment]
Brackets has this notion of a "Working Set" (i.e., files that are open) separate from the files in the filesystem--it usually shows the "Working Set" above the file system view, and we've removed it to reduce confusion.  What's happening with selection in the sidebar is that it's jumping up to the file in the "Working Set" and you can't see it.  We have this filed in Brackets here: https://github.com/humphd/brackets/issues/368

I think the easiest way to solve this is to not ever highlight the current file in the file tree, since we can't keep it highlighted without some massive reworking of Bracket's internals.  In Thimble, we have code to tell you which file you're looking at now, so maybe that's good enough?

**Comment by flukeout** [comment]
This is basically a dupe of #668 - so I'm going to close it.

**Comment by flukeout** [comment]
@humphd can we just put all the files in the working set so that they get the highlighted treatment when they're open?

If that's too much work, then I agree we should just remove the highlighting altogether. This wouldn't be ideal, as it's not super clear which file is open at any given time because the filename isn't very prominent in the Editor header bar.
