### ISSUE TITLE
Cache bust EVERYTHING!

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#641]
Cloudfront always seems to give us cached versions of different resources in our app and this causes stale content to be loaded. 

For e.g. in the "Your Projects" page, delete a project (it actually does delete the project) and then refresh the page...you still see the project there (when you try to delete the project again, you get an HTTP 404 because it was actually deleted before).

The solution (for now) for this is to send a random query string (probably current datetime) every time we make a request to the server.

**Comment by humphd** [comment]
I think this bug likely points at an opportunity for us to solve this higher up the stack.  CC'ing @simonwex and @jbuck for thoughts.

The background here is that we're hitting bugs on staging vs. local that relate to Cloudfront caching the responses for dynamic routes.  Obviously having cached resources is ideal, but could we improve things?  A bunch of Thimble is static content, and other bits aren't.  The way Facebook solves this, for example, is to separate things out by domain; so they serve static content from https://fbstatic-a.akamaihd.net/ and let dynamic content go direct to the app server.  Thimble has also changed a lot, with Bramble, since now serve almost all static front-end content from S3 inside an iframe on a second domain vs. serving the editor directly (i.e., Thimble is mostly a bunch of REST routes now, proxying access to publish.webmaker.org).

It seems like a bad idea for us to manual break cache for every dynamic route, and I wonder if we'd be better served by isolating our dynamic content (direct to ec2 app) vs. static content (cloudfront is great!)?  Probably there are good recipes for how one does this.

As an aside #621 deals with getting the browser to do a better job with cached resources.

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/issues/688 and https://github.com/mozilla/thimble.webmaker.org/issues/689 are two issues that we aren't able to control. Both seem to be because once you publish a project and open it in your browser, since it is a static resource, when we try to request it again, the browser uses the cached version. Hence, any steps in between like unpublishing or modifying and re-publishing are not reflected in what you see when you reload the project.

Another caching problem that we seem to primarily in Firefox is while making XHRs to our Thimble express server. Firefox always seems to load the cached version of the resource even if `Cache-Control` and `Expires` headers are sent. Right now our work-around for it is to send a query string parameter with the current date, so that every request appears to be different. However, this will not work in all cases since we won't be able to do this for HTTP redirects and when we do not want to dirty up the url that the client ends up seeing

**Comment by jbuck** [comment]
Without knowing the specifics, the best way of fixing this should be setting Cache-Control headers, which Cloudfront will respect. If you set `Cache-Control: private max-age=0` then Cloudfront shouldn't be caching anything, all requests will go straight through to the server. As a quick fix, you could simply set that header on everything single response, even static files. If this doesn't work, then I'm happy to help debug.

@humphd You could split up each app and host them via separate domains, but I think that's much more work that making good use of headers with a single CDN-fronted application.

**Comment by gideonthomas** [comment]
How do I set the headers for a published project? i.e. if a user accesses `makes.org/username/myproject/index.html`, how do we make sure that caching isn't used?

**Comment by jbuck** [comment]
When you publish content to S3 you can set the Cache-Control header (and others too!): http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests-request-headers

**Comment by gideonthomas** [comment]
Hmm interesting!
cc @sedge 
Thanks @jbuck, we'll try that
