### ISSUE TITLE
Create teaching kits and self-guided tutorials for starter makes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#685]
Started from @jgmac1106's awesome remix, and added a little more detail based on the new Thimble UX. 

http://bit.ly/1gr28xo

Would love feedback from @jgmac1106, @ldecoursy, and @omnignorant before going further with the other teaching kits.

**Comment by jgmac1106** [comment]
Realized the first kit was more for a group setting. For classrooms of one I am a fan of slidedecks with gifs and step by step directions such as: https://docs.google.com/presentation/d/1FyiPzYNY8Ol7S0UzRZ2kcanU86SqjIPghUXc-4fh_NM/edit?usp=sharing

**Comment by hannahkane** [comment]
I was definitely thinking of this as a group setting. Is there something that made you think we ought to focus on classrooms of one?

**Comment by hannahkane** [comment]
Have done a little more work in the gDoc.

Remaining TODOs:
 - [ ] Finalize "Keep Calm" kit (maybe close? Just needs some polishing)
 - [ ] Get more eyes on the "Comic Strip" kit; potentially add or replace activity with something suggested by the MLN team
 - [ ] Determine our Javascript activity and write the activity kit. 
 - [ ] Once kit contents are finalized, create teaching kits in Thimble or Github
 - [ ] Create self-guided tutorials for each activity
 - [ ] Create "Guide to Searching for Creative Commons-Licensed Images"

**Comment by chrislarry33** [comment]
That is a lot of work. can we prioritize p1/p2?. The new hire for curriculum should handle some of this, some we can ship soon.

**Comment by hannahkane** [comment]
Re-organized the ticket into P1 and P2. What is the timeline for the new hire? Ideally this is all ready to go in time for a late-August promo campaign (which means finalizing this stuff in advance of that, so engineers can build the landing page with this curated content).

**Comment by hannahkane** [comment]
This ticket blocks #697

**Comment by hannahkane** [comment]
Rather than have these Makes associated with a particular staff account, I'd like to create a "master" account from which to publish these "official" (homepage-worthy) makes. @ldecoursy - thoughts on that? Should it be associated with teachtheweb@mozillafoundation.org email address?

**Comment by ldecoursy** [comment]
We have a generic mozilla account we can use, can share login details with
you tomorrow.

**Comment by jgmac1106** [comment]
I tried to hash out the "selfie" kit. After reading through the An-me's
focus group interviews many stakeholders talked about the internet "safety"
as an issue. I tried to address this but more from a lens of shaping your
identity and discussing what and why we share. I also built in some stuff
on licensing your materials CC rather than just finding CC stuff. It is a
very rough draft.

I also tried to write a Creative Commons activity but only finished the
project. I did not want to write up the activity unless we were heading in
a direction folks liked. Could be way off.

 It was hard to come up with an activity that met the production centered
and collaborative requirements. I settled on trying to make a game or
scavenger hunt. I also pushed @cogdog's bookmarklet and Flickr. Not sure
how folks feel about that one.

Realized it doesn't fit back to school theme but the placeholder cards
would be easy to switch. Just have to switch images with, "Find a picture
of a school in another country you can use but can not change."

-----------------------------------------------------
Another idea (down the road and beyond scope of this issue: We could also
instead have users play the game to  create a collage about "benefit of
open web" This would mean the three thimble makes, down the road could be
folded into an open practices teaching:
*distinguishing between open and closed licensing
*making we resources available under an open license
*advocating for an open web

Would just need to hit "Contribute to contribute to an open source project"
to get all the skills under the open practices competency.

**Comment by hannahkane** [comment]
We have our starter makes and kits; though polishing is still allowed. :)
