### ISSUE TITLE
Thimble shouldn't serialize file data as JSON in server responses

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#731]
The upload case was the worst offender with wasted bandwidth, but we can further optimize the user experience by finding a way around sending files through JSON.

**Comment by humphd** [comment]
CC'ing @DavidBruant, who was discussing this topic on twitter this weekend, https://twitter.com/DavidBruant/status/627419396366057473.

@DavidBruant, the thing I'd like your thoughts on here is how we might leverage protocol buffers in the new Thimble, which needs to serialize entire file trees (i.e., we support dirs/files now).  With uploads we've used `FormData` and just attach our `ArrayBuffers` directly, which works nicely.  But for the case of loading the file tree from the server initially, we currently serialize node `Buffer`s to JSON, which is a massive size increase.  It would be interesting to switch that can a) reduce size; b) support binary (we want `Buffer` (node-side) and `ArrayBuffer` (browser); c) doesn't add a massive cost for "unpacking".

If you have thoughts, I'd appreciate it.  Thanks!

**Comment by humphd** [comment]
For reference, here is the form of what we currently send back to the client in order to initialize a project:

```js
{
  project: {
    title: "The Project Title",
    created: ISODate,
    updated: ISODate,
    userId: 1234
  },
  files: {
    "/some/path.html": {
      buffer: /* binary data, currently JSON */
      path: "/some/path.html"
    },
    "/some/other-path.js": {
      buffer: /* binary data, currently JSON  */
      path: "/some/other-path.js"
    },
    "/some/image.png": {
      buffer: /* binary data, currently JSON  */
      path: "/some/image.png"
    },
    ...
  }
}
```

**Comment by DavidBruant** [comment]
> But for the case of loading the file tree from the server initially, we currently serialize node Buffers to JSON

I'm not sure I understand that part. Why do you already have the tree as a `Buffer`? Is it stored as binary in your database?

In any case, for protocol buffers, as far as I know, the only out-of-the-box way to leverage them in both client and server is to use https://github.com/mafintosh/protocol-buffers with browserify. There are lots of possible optimizations and room for improvements upon this implementation, but that's a topic for another day.

> a) reduce size

From experience, protocol buffers are amazing at shrinking data when the data is lots of numbers. It's much less efficient if the data is long strings (or long binary segments). But in your case, your biggest saving will be in the ability to keep in binary something you already have in binary.
In any case, the best thing is to measure. From the client to the server, measure the raw size (since there is no gzip compression in HTTP POST). Compare gzipped for a server response.

> b) support binary (we want Buffer (node-side) and ArrayBuffer (browser);

As demonstrated in https://github.com/DavidBruant/protobuf-client/blob/9b33f62bd8a1e1669c8ca0a1b591757add0106c1/client.js#L13 the library returns a UInt8Array on the client side (despite my misleading comment :-/) when encoding binary data (and obviously, it returns a Buffer on the Node.js side). Feel free to read this repo, it's fairly short and simple and ask questions if something isn't clear.

> c) doesn't add a massive cost for "unpacking".

I cannot make any promise here. I guess it'll be hard to make sure without measuring. Protocol buffers as they exist have the same problem than JSON for unpacking which is that the entire data structure must be read for an object to be decoded (unlike FlatBuffers apparently). This costs less than JSON because there is usually much less data to read and I would guess the parsing code is more efficient (because it's specialized for the data structure), but again, it's hard to know in advance.

For your `.proto` files, you can go all the way to "protobuf" the entire data structure. It would look like something like that:

```protobuf
syntax = "proto3";

message ProjectInit{

  message Project {
    string title = 1;
    int32 created = 2; // there is no native date type in protobuf
    int32 updated = 3;
    int32 userId = 4;
  }

  message File{
    string path = 1;
    bytes buffer = 2; // a way to embed custom encoded binary in protobuf
  }

  Project project = 1;
  // this will make an array you'll need to traverse to make a dictionary object again.
  repeated File files  = 2 [packed=true]; 
}
```

Re `this will make an array you'll need to traverse to make a dictionary object again.`, from my short experience, it's usually necessary to preprocess the data a little bit before protobuf-encoding it, so for instance, make arrays instead of dictionary objects. Or for dates, you may want to turn the date into an integer (not necessarily a UNIX timestamp) where you truncate to a level of accuracy that is not the millisecond and that doesn't start at 1970 (protobufs encodes smaller ints more efficiently).

**Comment by sedge** [comment]
We use tars! Closing
