### ISSUE TITLE
Allow multiple thimble instances per browser session

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#750]
The application is configured in such a way that it can only track one opened project at a time. Opening the application in more than one window/tab in the same browser session would have unexpected and disastrous results.

**Comment by jgmac1106** [comment]
This really shouldn't be an issue in many of the makes with the new
tutorial.html in the same file system. In the past Thimble Teaching Kits
telling people to open up the same make in two different tabs was a common
(and not the best) strategy mentors used when making tutorials and teaching
kits.

**Comment by sedge** [comment]
@jgmac1106 In the case where a user *does* open the new thimble in two tabs, it will result in loss of data. Better that we prevent it IMO

**Comment by jgmac1106** [comment]
I agree. We just need to educate the mentors not to build that into their
workflow. Unrelated to tutorials I know I currently often open up two
different makes at the same time so I can compare code.

I might not remember how to do something so I will go and open a second
project so I can see how someone else wrote the code I am trying to do.

**Comment by sedge** [comment]
@gideonthomas Can you clarify why this is necessary from a technical perspective?

**Comment by gideonthomas** [comment]
We should basically do something like what netflix does in terms of having only one active instance of netflix open. 
From thimble's POV, we store project metadata for the current user in a session variable. If Thimble is opened in another tab and another project is opened, this will overwrite the existing session variable with the new project that was selected. Making changes in the new tab will be fine! But, making changes in the old tab will result in data corruption (for the new project) if the file path matches as it will persist the file with the new project metadata instead of the old one.
One very obvious case where this will become a big UX problem is in the case of remix. **If you are authenticated** and have thimble open in one tab with the default project and then in another tab, you remix another project, you will have two instances of thimble open with two different project contexts putting you in the same situation as above.

**Comment by gideonthomas** [comment]
cc @humphd re: note above. I think this should be P1 because of that

**Comment by humphd** [comment]
Sounds good to me.

**Comment by hannahkane** [comment]
As I mentioned at stand-up today, I think it's probably a fairly common use case to have multiple Thimble tabs open at once. For the reasons @gideonthomas and @jgmac1106 suggest above (remixing and comparing code across projects). It's also a downgrade from the way Thimble currently works, and would likely be an unpleasant surprise to current Thimble users.

I'd like to prioritize a fix to the underlying challenge so that users can open multiple Thimble tabs at once without unintentionally overwriting project files.

**Comment by sedge** [comment]
@hannahkane The one restriction I'd like to suggest is that we shouldn't allow the same project to be open in two places. Is that okay?

**Comment by hannahkane** [comment]
I think that would be understandable to users, so yeah, that's fine. We should design UX around that use case. /cc @flukeout

**Comment by cassiemc** [comment]
fwiw I often have two google docs open at once, to look at content in different spots in the document. I wonder if people do the same for thimble?

**Comment by sedge** [comment]
@cassiemc Good point! I'd lean towards extending brackets to allow that vs. having the same project open in two separate thimble instances.

**Comment by sedge** [comment]
#627 will make this happen for anonymous users.
