### ISSUE TITLE
Should there be a link to a discourse category or instance just for Thimble?

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#767]
I spoke with @flukeout about this during user testing but I am wondering if we should build a community based help channel right into Thimble.

My thinking was a link in the footer to a discourse category on discourse.webmaker.org or a new instance just for Thimble. 

I use discourse currently when I need coding help (I stick questions in the Training category) and usually get a quick response. 

Down the road after launch there could be a "stack overflow" like community grow using discourse (when its healthy again) where users, learners, and teachers help each other out.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. I'm going to pause this because we're having some challenges with Discourse right now. 

There is a question in the FAQ (#567) about how to get help. We can potentially add Discourse to that.

I'd prefer to link to a particular thread rather than a new instance of Discourse, because maintaining multiple instances could be problematic.
