### ISSUE TITLE
Bramble sometimes won't finish loading

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#777]
https://www.dropbox.com/s/v97w0tbuv8k40yl/Screenshot%202015-08-04%2010.38.24.png?dl=0

I think it get stuck and times out waiting on something, not sure what.  I see it sometimes though, and it's bad.

**Comment by humphd** [comment]
Clearning cookies, storage, etc. seems to fix it.

**Comment by sedge** [comment]
@humphd This happened in a project with a complex file tree correct? When I repeated the STR I found that heroku started reporting that bramble had run out of memory, and was using paging. I think this drastically affects performance, resulting in a timeout on the client first, and then on the server for the `/initializeProject` call that drags on past 30 seconds.

@gideonthomas We should try and pin down where the memory use accumulates. My guess is it occurs when we try to retrieve the entire project from the publish server, including the file contents.

**Comment by gideonthomas** [comment]
So,the cookie size issue seems to have been temporarily fixed. Now we run out of memory because we are sending a collection of project file buffers all at once from server->client as a json serialized object. We should change this so that the server sends the list of files that need to be downloaded first to the client and then the client can request each file individually.

**Comment by sedge** [comment]
@gideonthomas See: https://github.com/mozilla/thimble.webmaker.org/issues/798

**Comment by gideonthomas** [comment]
Right, keeping this issue open until we figure out a long-term solution for the cookie problem

**Comment by humphd** [comment]
Part of this is changing to using a `.tar` file to seed the content in the project.  I've done some work on this here https://github.com/humphd/brackets/pull/416
