### ISSUE TITLE
Published project doesn't reflect changes in editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#792]
Here's a published project, note the purple background:
![image](https://cloud.githubusercontent.com/assets/25212/9098870/4f739e46-3b81-11e5-96a4-425460035a11.png)

It's published here, with none of the changes reflected...
http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/135/

**Comment by sedge** [comment]
@flukeout This issue is related to #788. 

@humphd The pathing issues also cause a new file to be created instead of updating the old one when you make the change, though you can't see it unless you refresh the page:

![screen shot 2015-08-06 at 10 32 39 am](https://cloud.githubusercontent.com/assets/1616860/9114195/923bfdae-3c26-11e5-9c97-ec2c53b085eb.png)
![screen shot 2015-08-06 at 10 33 05 am](https://cloud.githubusercontent.com/assets/1616860/9114196/923fcb3c-3c26-11e5-9725-0a581849d986.png)

**Comment by flukeout** [comment]
Looks good - project looks as expected when published!
