### ISSUE TITLE
Support old thimble remix URLs

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.webmaker.org#793]
Can we support opening the old thimble content in the new editor?

I have this old project:
https://simon.makes.org/thimble/fire

When I click on remix, it opens this:
https://thimble.webmaker.org/project/29244/remix

What would be involved in maintaining remix-ability for old thimble makes in the new codebase?

/cc @jbuck @sedge @hannahkane

**Comment by hannahkane** [comment]
Just a note that we don't actually need to solve this for as long as we have the path to "old" Thimble, so I'm removing from MVP.

**Comment by sedge** [comment]
We definitely could. I'd guess that this won't be MVP, since our [priority one issue list]() is already huge, but I'll raise it at our next standup to get some opinions and see if we can triage it reasonably.

Off the top of my head:

1. We'd need to make sure an RPC route for returning an old make's contents without authentication existed on old-thimble
2. We'd need to have an RPC route on thimble-beta that could be passed an old-thimble make identifier, which would hit the old-thimble route described above

**Comment by humphd** [comment]
Closing in favour of #509.
