### ISSUE TITLE
Got an "External Changes" error

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#804]
While editing a project, I got the following error..
![image](https://cloud.githubusercontent.com/assets/25212/9123956/f3a9dc84-3c47-11e5-8c06-61e2eef0e9c4.png)

What I remember doing
* Renaming the project
* Changing a few styles in style.css
* Changing some text in index.html
* Switching back to style.css <- this is when it happened

**Comment by humphd** [comment]
This is a safety check within Brackets, and it happens when the file's timestamp is different from the last time Brackets looked at the file on disk (it caches files in memory).  This means that, somehow, the file was modified between writes, and not by you.  Why that would happen is a good question.

**Comment by humphd** [comment]
Did you have the editor open in 2 different tabs?  If so, that would be one way to trigger this, since they would be sharing the same filesystem.  We're moving to a world where tabs don't share the same project folder, but it's not done yet.

**Comment by flukeout** [comment]
I'm not sure - I'll close for now and re-open if i notice it again. I've only seen it once ever.

**Comment by flukeout** [comment]
If there is a chance that this error will show due to any kind of circumstance down the road, let's improve the error message though.
