### ISSUE TITLE
Projects don't publish if any file's path has a space in it

### ISSUE THREAD

**Issue by k88hudson** [mozilla/thimble.webmaker.org#862]
STR: 

1. Create new user account
2. Create a new project
3. Edit some text, create a folder, create a new file
4. Click publish, add a description

Expected: Publish succeeds
Actual: Nothing happens, dialog box stays open

Console has these errors:

```
PUT https://thimble-beta.webmaker.org/publish 500 (Internal Server Error)

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
[Bramble] Failed to send request to publish project to the server with:  Internal Server Error

Uncaught TypeError: Cannot read property 'remove' of nullPopupMenu.close
bramble-popupmenu.js:39
```

**Comment by sedge** [comment]
@k88hudson Can you reproduce this with an existing user? Also, can you describe exactly what folder and file you created? And how?

**Comment by ldecoursy** [comment]
I had this same problem. When I clicked "Publish," it said "Publishing," but then defaults back to Publish and I don't receive a URL for my project.

**Comment by sedge** [comment]
@ldecoursy Thanks for the feedback! 

Can you tell me what files/folders you added? Also, what's your id.webmaker.org username? @k88hudson Can you tell me the username you used when you ran into this issue?

**Comment by ldecoursy** [comment]
Username is lainie, I added an image from my desktop 
![screen shot 2015-06-21 at 8 11 06 am](https://cloud.githubusercontent.com/assets/4885898/9309530/44d17304-44d8-11e5-8ca5-113e2e1d5c6b.png)

**Comment by sedge** [comment]
@ldecoursy Thanks for the quick response. Last question! What was the filename of the image after you added it to the project?

**Comment by k88hudson** [comment]
username: asdasdsad2ewasdd
project: https://stuff.webmaker.org.s3.amazonaws.com/k88/project.zip

**Comment by sedge** [comment]
Hmm... That project tree looks identical to the default. I guess the new file didn't end up being saved?

**Comment by k88hudson** [comment]
@sedge do you mean mine?

**Comment by sedge** [comment]
@k88hudson Yes, but I was wrong. Ignore my comment ^.^

**Comment by sedge** [comment]
@k88hudson It looks like the editor can't publish projects containing folders with spaces in their names. I'll whip up a patch for this. Thanks for reporting!

@ldecoursy I won't be able to confirm what's causing your issue until I know the name of the image you uploaded.

**Comment by ldecoursy** [comment]
![screen shot 2015-08-17 at 1 34 44 pm](https://cloud.githubusercontent.com/assets/4885898/9311521/c2737f4e-44e4-11e5-8b64-4e46a097e832.png)

**Comment by sedge** [comment]
@humphd So, IMHO the simplest way to solve this requires:

1. On publish.wm.o, transforming file paths with spaces to be url encoded
2. On thimble.wm.o, transforming css/html links to resources to be url encoded 

Having to make sure there aren't spaces in a path when you upload a file seems like a huge pain. This doesn't affect project persistence though, only publish. 

cc: @gideonthomas

**Comment by humphd** [comment]
The solution here is to `encodeURICompenent` before you put a path on a URL destined for publish, and then decide it when you get it (likely automatic).  This probably needs to happen in the Thimble server code that talks to publish. The Thimble client and brackets don't need to care.

On Aug 17, 2015 2:28 PM, Kieran Sedgwick <notifications@github.com> wrote:

@humphd<https://github.com/humphd> So, IMHO the simplest way to solve this requires:

  1.  On publish.wm.o, transforming file paths with spaces to be url encoded
  2.  On thimble.wm.o, transforming css/html links to resources to be url encoded

Having to make sure there aren't spaces in a path when you upload a file seems like a huge pain. This doesn't affect project persistence though, only publish.

cc: @gideonthomas<https://github.com/gideonthomas>

**Comment by humphd** [comment]
@sedge I tried reproducing this one locally, and I can see it fail.  I drag a photo with spaces in the filename into the editor, and everything is fine; I see this in publish:

```
[2015-08-18T05:55:36.157Z]  INFO: publish.webmaker.org/77801 on hospitality.local: Successfully uploaded /dh/12/27331 banner blue bike.jpg
```

Note how it got the filename right, `27331 banner blue bike.jpg`.  However, when I look at what's stored in my local noxmox/S3, I see these two files:

```
27331%20banner%20blue%20bike.jpg
27331%20banner%20blue%20bike.jpg.meta
```
Now you can see it's been URI encoded, and when the server goes looking for the file with spaces vs. `%20`, it won't find the file.  So I'd say the problem is in whatever code is writing this stuff to S3 vs. the Thimble+Publish servers.

Looking at noxmox, I see https://github.com/nephics/noxmox/blob/master/auth.js#L176-L190, which looks to be the issue, and is being called on the `resource` passed with the request, here: https://github.com/nephics/noxmox/blob/master/nox.js#L68.

I'd get @jbuck involved to help you think this through.  Somewhere along the line we are getting the encode/decode dance wrong, such that the file the browser ends up requesting for a published make isn't found in the S3 bucket.

**Comment by humphd** [comment]
Hilariously, it looks like @jbuck may indeed be the right person to ask about this, given https://github.com/Automattic/knox/commit/6f2ad0d140f77bf3a19a66fb5aadfee54918d320, which I found in the issues filed against noxmox by @Pomax, related to improper URL encoding and unicode.  Small world.

**Comment by jbuck** [comment]
I don't know where this error could be, but I'd highly recommend moving away from noxmox and knox, and switching to aws-sdk and using a S3 bucket

**Comment by sedge** [comment]
@humphd I'm fairly certain that the issue is that s3 keys /must/ be url encoded. If that's the case, then we need to transform links to project resources in one of two places: In thimble, before a file is persisted (encoded) and after one is fetched (decoded) OR on publish itself before a file is published (encoded). 

I'll do more research
