### ISSUE TITLE
Implement a short-lived project lock system for multi-tab safety

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#879]
Once we are able to open different projects in different tabs, we come across two edge cases:
* Open two tabs with the same project. Changes in one will not be reflected in the other and there will be a race for which one is considered the "source of truth" wrt project contents (name, files, etc.) so there is a 100% chance of data corruption.
* Opening a project in one tab and in another, looking at the "My Projects List" and deleting the project there. Any changes made to the project in the original tab will fail.

**Comment by hannahkane** [comment]
For both cases, can we prevent the user from taking the corrupting action by throwing a warning? From a UX perspective, I think that works. @flukeout?

**Comment by gideonthomas** [comment]
@hannahkane we were also thinking along the same lines (but we were thinking about making it impossible to open the same project in more than one tab). The technical challenge for both remains the same, we don't have a good way to let other tabs/browsers know what projects are open.
cc @humphd

**Comment by sedge** [comment]
What if we flagged which projects were open with an `xattr`, and also included an expiry? Each tab would be responsible for keeping the expiry refreshed, and if `/projects` was hit, it could display all non-locked or expired projects. This won't help even a little bit with multi-browser compatibility, but it would fix multi-tab.

**Comment by humphd** [comment]
You basically need to implement a short-lived lock (either in the fs, or in `localStorage`), which the owning tab updates (e.g., storing `Date.now()`) every N ms.  When other tab(s) try to open that same project, they inspect the lock, check the time and see if it's stale (i.e., exceeds the N ms threshold), in which case they acquire the lock; otherwise they throw up some kind of UI that says, "This project is already open...".

That's kind of how https://github.com/npm/lockfile works.  The down side to this is that you can only make this work per-browser on a given machine.  Probably that's OK though, especially for MVP.

**Comment by sedge** [comment]
As for the delete case, the owning tab will know if the path disappears (since reading the xattr will return `ENOENT`) and can redirect to /projects

**Comment by humphd** [comment]
Whoever implements this, make sure that we don't get into a situation where we hold a lock after a tab closes, and the user tries to open the project in a second tab, we say that it's already open.  We should either set the lock timeout to be pretty short, or try to remove it on close (might be impossible if it's an async call).

**Comment by sedge** [comment]
:+1:
