### ISSUE TITLE
Identify every thimble instance uniquely to avoid users from opening the same project in more than one tab

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#916]
Our lock system on projects that indicate which project is open or not depends on each tab updating the lock stored in localStorage after a set interval.

This is a bad idea as we run into quite a number of timing issues where a project is shown as locked, but actually isn't or vice-versa.

An e.g. is right here:
![time-based-checks](https://cloud.githubusercontent.com/assets/5816130/9449762/c823634e-4a72-11e5-9872-93fb6e0716b6.gif)
Both Green and Blue are incorrectly shown as unlocked, even though they are open in another tab. I can even open Blue in Thimble and make changes to it (which is bad).

I don't know what the best solution out here is, but I do think we shouldn't rely on time.

**Comment by humphd** [comment]
I've been thinking about this tonight, and I think I have an answer.  We can't rely on `localStorage` for the lock, because it doesn't provide atomic operations, and you'll eventually have a race like the one above.  I've been trying to decide if we could do what we need with inter-tab communication, and everything has problems.

What we really need is a time-delta based lock file, and we actually already have exactly what we need.  Whenever we write any data to a project, we also update the project metadata stored on the xattr of the project folder.  If we examine the `mtime` on the project root, we know roughly when the project last had any of its contents saved.  This isn't perfect, because it allows you to have a tab open to a project that just sits idle forever (no changes, no saving); I would argue that this is basically the same as not having it open at all, since Brackets will detect filesystem changes when it regains focus and you try to write something.

What if we did this:
* When you open the project folder, you first `stat` it.
* If the project folder doesn't exist, then you make it, and you start using it--you're the only one using it right now (i.e., you have the "lock").
* If the project folder does exist, you inspect `mtime`, looking to see whether it falls within some delta (we currently autosave every 5s, so that's one number to consider).
* If `mtime` was last updated *within* the delta, you prompt the user and let them know that it's not wise to edit a project in multiple tabs at once (i.e., you don't get the "lock").
* If `mtime` was last updated *outside* the delta, you assume that the "lock" is stale, and you go ahead and open it and start using it.

I think this basically covers the most obvious cases, and does so without requiring us to build any new infrastructure--we just use the project root as a lock file, and we're done.

**Comment by humphd** [comment]
From discussions today, here's some more thoughts:

* Thimble client starts, you either generate a UUID or get a UUID from sessionStorage.  Each tab has a UUID.
* Look at the project root
    * If it doesn't exist, you make it, and you own it.  And you write your client UUID to the metadata as "lastClient"
    * If it does exist, you look at the client UUID, and if it's yours, you do nothing, you keep going.
    * If it does exist, and UUID isn't yours, you look at mtime and if > delta, you put your UUID in the metadata, and use it
    * If iit exists, and UUID isn't yours, and mtime < delta, you prompt the user and say, "Careful!"
* Every time we write to the xattr, we'd re-stamp the metadata with our UUID

* If you delete a project on the Projects page, we send a DELETE to Thibmle/Publish, but also do a sh.rm() on the project root to blow it away
* Each Thimble instance will need to listen for the project root folder being removed, and prompt the user to say that this project has been removed.  Maybe a prompt followed by a redirect to the Projects page.

We're going to solve this after launch.
