### ISSUE TITLE
Thimble doesn't recognise Firefox as Firefox.

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#977]
![screenshot 87](https://cloud.githubusercontent.com/assets/177243/9560082/9db600ce-4db7-11e5-8c67-aef686ebff41.png)

FF 40.0.3 (win7)

**Comment by humphd** [comment]
Trying a new UA parser lib in https://github.com/mozilla/thimble.webmaker.org/pull/978

**Comment by humphd** [comment]
This really sucked, but I think I've fixed it.  I tried a different UA parsing lib (https://github.com/mozilla/thimble.webmaker.org/pull/978) but that didn't solve it.  In the end I moved the detection to the client, because I think the UA is getting messed up by cache servers or the like (see https://github.com/mozilla/thimble.webmaker.org/commit/83156b1691acad49452763f5d185eaca9477f609).

If people could try loading staging on various browsers/machines they use, and make sure you don't get this warning when you expect it, I'd appreciate it.  cc @flukeout, @sedge, @gideonthomas.

**Comment by Pomax** [comment]
checks:
- [x] FF 40.0.3/win7
- [x] Chrome 44.0.2403.157 m/win7
- [ ] IE 11 on win7 reports "oh no!" with script errors once you click through
- [x] Opera 31.0.1889.174/win7
- [x] Vivaldi 1.0.219.50 (Developer Build)/win7 (seriously? yep. Flat out works)
